<script setup lang="ts">
import {ref,onMounted,onBeforeUnmount} from 'vue';
import UiButton from './UiButton.vue';
import type {AnnouncementPage} from '../../../../packages/contracts/generated';
const props=defineProps<{instrumentId:string}>();
const data=ref<AnnouncementPage|null>(null),busy=ref(false),error=ref('');
const end=ref(new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai'}).format(new Date()));
const start=ref(new Date(Date.parse(end.value+'T00:00:00Z')-90*86400000).toISOString().slice(0,10));let closed=false;
const message=(e:unknown)=>(e instanceof Error?e.message:String(e)).replace(/^Error invoking remote method '[^']+': Error: /,'');
async function read(offset=0){if(!window.stock)return;const next=await window.stock.readAnnouncements(props.instrumentId,offset);if(!closed)data.value=next}
async function page(offset=0){if(busy.value)return;busy.value=true;error.value='';try{await read(offset)}catch(e){error.value=message(e)}finally{busy.value=false}}
async function sync(){if(!window.stock||busy.value)return;busy.value=true;error.value='';try{await window.stock.syncAnnouncements(props.instrumentId,start.value.replaceAll('-',''),end.value.replaceAll('-',''));await read()}catch(e){if(!closed)error.value=message(e)}finally{busy.value=false}}
async function open(id:string){try{await window.stock?.openAnnouncement(props.instrumentId,data.value?.offset??0,id)}catch(e){error.value=message(e)}}
onMounted(async()=>{await page();if(!closed&&!error.value&&!data.value?.snapshotId)void sync()});onBeforeUnmount(()=>{closed=true});
</script>
<template><section class="announcement-panel"><form @submit.prevent="sync"><label>开始 <input type="date" v-model="start" :disabled="busy" required></label><label>结束 <input type="date" v-model="end" :disabled="busy" required></label><UiButton icon="refresh" icon-only :disabled="busy">刷新公告</UiButton></form><p v-if="busy" role="status">正在读取公告…</p><p v-if="error" role="alert">{{error}} <UiButton icon="refresh" icon-only :disabled="busy" @click="sync">重试公告</UiButton></p><p v-if="data?.snapshotId" class="announcement-source">Tushare · {{data.start}} — {{data.end}} · {{data.total}} 条</p><ul v-if="data?.items.length"><li v-for="item in data.items" :key="item.id"><time :title="item.publishedAt??item.date">{{item.date}}</time><button @click="open(item.id)" :title="item.url">{{item.title}}</button><UiButton icon="chevron" icon-only @click="open(item.id)">打开公告原文 {{item.title}}</UiButton></li></ul><p v-else-if="!busy&&!error">{{data?.snapshotId?'该日期范围没有公告':'暂无已保存公告'}}</p><div v-if="data&&data.total>50" class="announcement-pages"><UiButton icon="chevron" :disabled="busy||data.offset===0" @click="page(Math.max(0,data.offset-50))">上一页</UiButton><span>{{Math.floor(data.offset/50)+1}} / {{Math.ceil(data.total/50)}}</span><UiButton icon="chevron" :disabled="busy||data.offset+50>=data.total" @click="page(data.offset+50)">下一页</UiButton></div></section></template>
<style scoped>.announcement-panel{padding:20px 24px;min-width:0}.announcement-panel form{display:flex;align-items:center;flex-wrap:wrap;gap:12px}.announcement-panel label{display:flex;align-items:center;gap:6px;font-size:12px;color:var(--muted)}.announcement-panel input{max-width:145px}.announcement-panel p{font-size:12px;color:var(--muted);overflow-wrap:anywhere}.announcement-panel [role=alert]{color:var(--danger)}.announcement-panel ul{list-style:none;padding:0;margin:16px 0}.announcement-panel li{display:flex;align-items:center;gap:12px;padding:10px 0;border-bottom:1px solid var(--line)}time{font-size:12px;color:var(--muted);flex-shrink:0}.announcement-panel li>button:not(.ui-action){flex:1;text-align:left;overflow-wrap:anywhere;min-width:0;font-size:13px;padding:0}.announcement-pages{display:flex;align-items:center;justify-content:flex-end;gap:8px;font-size:12px}</style>
