<script setup lang="ts">
import {ref,onMounted,onBeforeUnmount} from 'vue';
import type {CashState,CashRecord,CashWriteRequest,CashEvent} from '../../../../packages/contracts/generated';
import UiButton from './UiButton.vue';
import {connectionError} from './connection-error';
const data=ref<CashState|null>(null),busy=ref(false),error=ref(''),notice=ref(''),kind=ref<CashEvent['kind']>('balance'),amount=ref(''),date=ref(new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai'}).format(new Date())),target=ref<string|null>(null);
let closed=false,generation=0,pending:CashWriteRequest|null=null;
const labels={balance:'日终余额',deposit:'入金',withdrawal:'出金',fee:'额外费用'};
async function load(){const current=++generation;try{const value=await window.stock!.readCash();if(!closed&&current===generation)data.value=value}catch(e){if(!closed&&current===generation)error.value=connectionError(e,'data')}}
function correct(row:CashRecord){kind.value=row.event.kind;amount.value=row.event.amount??'';date.value=row.event.date;target.value=row.id;pending=null;notice.value=''}
function reset(){target.value=null;amount.value='';pending=null}
async function save(voidId:string|null=null){if(busy.value||!data.value)return;busy.value=true;error.value='';notice.value='';const base={revision:data.value.revision,event:voidId?null:{kind:kind.value,date:date.value,amount:amount.value.trim()||null},supersedes:voidId??target.value,voided:!!voidId};
 const compare=({revision,requestId,...value}:CashWriteRequest)=>JSON.stringify(value);
 if(!pending||compare(pending)!==compare({...base,requestId:''}))pending={...base,requestId:crypto.randomUUID()};
 try{await window.stock!.writeCash(pending);reset();notice.value=voidId?'记录已作废':'现金账本已更新';await load()}catch(e){error.value=connectionError(e,'data');if(String(e).includes('STALE_CASH')){pending=null;await load()}}finally{busy.value=false}}
const unsubscribe=window.stock?.onDataChanged(domain=>{if(domain==='holdings'&&!busy.value)void load()});onMounted(load);onBeforeUnmount(()=>{closed=true;generation++;unsubscribe?.()});
</script>
<template><section class="cash-ledger"><div class="cash-totals"><div><small>现金（元）</small><strong>{{data?.balance??'—'}}</strong></div><div><small>总资产（含现金）</small><strong>{{data?.totalAssets??'—'}}</strong></div><span v-if="data?.state==='missingBalance'">尚未核对现金余额</span><span v-else-if="data?.state==='unreconciledPosition'">持仓有余额调整，现金待核对</span></div><p v-if="error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p><details class="cash-editor"><summary>管理现金</summary><form @submit.prevent="save()"><fieldset :disabled="busy||!data"><div class="cash-fields"><label>类型<select v-model="kind"><option v-for="(label,value) in labels" :key="value" :value="value">{{label}}</option></select></label><label>日期<input type="date" v-model="date" required></label><label>金额（元）<input v-model="amount" inputmode="decimal" :required="kind!=='balance'" :placeholder="kind==='balance'?'未知可留空':''"></label><UiButton type="submit" icon="check">{{target?'保存更正':'记入账本'}}</UiButton><UiButton v-if="target" type="button" icon="close" @click="reset">取消更正</UiButton></div></fieldset></form><p v-if="kind==='balance'" class="cash-note">日终余额包含当天流水，从次日开始计入后续交易。</p><p v-else-if="kind==='fee'" class="cash-note">只记录交易费用以外的支出，避免重复扣除。</p><p v-if="data?.balanceDate" class="cash-note">余额起点 {{data.balanceDate}} · 此后入金 {{data.deposits}} · 出金 {{data.withdrawals}} · 额外费用 {{data.fees}} · 交易净现金 {{data.tradeNet}}</p><div class="cash-history"><div v-for="row in data?.events.slice().reverse()" :key="row.id" class="cash-row" :class="{inactive:!row.active}"><time>{{row.event.date}}</time><span>{{labels[row.event.kind]}}{{row.voided?' · 作废':!row.active?' · 已替代':''}}</span><span>{{row.event.amount??'未知'}} 元</span><div v-if="row.active" class="cash-actions"><UiButton icon="edit" icon-only :disabled="busy" @click="correct(row)">更正现金记录</UiButton><UiButton icon="close" icon-only :disabled="busy" @click="save(row.id)">作废现金记录</UiButton></div></div></div><p v-if="data?.hasOlder" class="cash-note">显示最近 200 条；更早的记录仍保留在账本中。</p></details></section></template>
<style scoped>.cash-ledger{margin:20px 0;border-top:1px solid var(--line);padding-top:16px}.cash-totals{display:flex;align-items:center;gap:28px;flex-wrap:wrap}.cash-totals>div{display:grid;gap:6px}.cash-totals strong{font-size:22px;font-variant-numeric:tabular-nums}.cash-totals small,.cash-totals>span,.cash-note{color:var(--muted);font-size:12px}.cash-editor{margin-top:16px}summary{cursor:pointer}.cash-fields{display:flex;gap:12px;flex-wrap:wrap;align-items:end}fieldset{border:0;padding:0;margin:14px 0;min-width:0}label{display:flex;flex-direction:column;gap:6px;font-size:12px}input{width:150px;max-width:100%}.cash-history{max-height:320px;overflow:auto}.cash-row{display:flex;gap:16px;align-items:center;padding:9px 0;border-bottom:1px solid var(--line);font-size:12px;flex-wrap:wrap}.inactive{color:var(--muted)}.cash-actions{display:flex;margin-left:auto}.cash-note{line-height:1.6}[role=alert]{color:var(--danger)}[role=status]{color:var(--muted)}</style>
