<script setup lang="ts">
import UiButton from './UiButton.vue';
import {onMounted,ref} from 'vue';
const desktop=Boolean(window.stock),setting=ref(false);
const state=ref<{readiness:string;mode:string|null}|null>(null),mode=ref<'elevated'|'unelevated'>('elevated'),busy=ref(false),error=ref('');
async function run(setup=false){if(!window.stock||busy.value)return;busy.value=true;setting.value=setup;error.value='';try{state.value=await (setup?window.stock.codexSandboxSetup(mode.value):window.stock.codexSandboxStatus());if(state.value.mode==='elevated'||state.value.mode==='unelevated')mode.value=state.value.mode}catch(e){error.value=e instanceof Error?e.message:String(e)}finally{busy.value=false}}
const policy=ref<{networkAccess:boolean;mode:'ask'|'auto-review'|'full-access'}>({networkAccess:true,mode:'ask'}),policyBusy=ref(false),policyReady=ref(false),policyError=ref('');let savedPolicy={...policy.value};
async function loadPolicy(){policyBusy.value=true;try{policy.value=await window.stock!.copilotPolicy();savedPolicy={...policy.value};policyReady.value=true}catch{policyError.value='无法读取执行权限。'}finally{policyBusy.value=false}}
async function savePolicy(){policyBusy.value=true;policyError.value='';try{policy.value=await window.stock!.saveCopilotPolicy({...policy.value});savedPolicy={...policy.value}}catch(e){policy.value={...savedPolicy};policyError.value=String(e).replace(/^.*Error: /,'')}finally{policyBusy.value=false}}
onMounted(()=>{void run();if(window.stock)void loadPolicy()});
</script>
<template><section class="settings-section sandbox-settings"><div class="section-description"><h2>权限与沙箱</h2></div><div class="settings-form"><div class="setting-row"><label for="copilot-approval">默认权限</label><select id="copilot-approval" v-model="policy.mode" :disabled="policyBusy||!policyReady" @change="savePolicy"><option value="ask">请求批准</option><option value="auto-review">帮我审批</option><option value="full-access">完全访问权限</option></select></div><div v-if="policy.mode!=='full-access'" class="setting-row"><label for="copilot-network">允许联网</label><input id="copilot-network" v-model="policy.networkAccess" class="setting-switch" type="checkbox" role="switch" :disabled="policyBusy||!policyReady" @change="savePolicy"/></div><p v-if="policy.mode==='full-access'" class="setting-muted">允许访问项目外文件和网络。</p><p v-if="policyError" role="alert">{{policyError}} <UiButton v-if="!policyReady" icon="refresh" @click="loadPolicy">重试</UiButton></p><p role="status">{{busy?(setting?'正在应用，请留意系统授权提示…':'正在加载…'):state?.readiness==='ready'?'已就绪':state?.readiness==='updateRequired'?'需要更新':'尚未配置'}}</p><div class="setting-row"><label for="sandbox-mode">隔离方式</label><select id="sandbox-mode" v-model="mode" :disabled="busy"><option value="elevated">标准隔离</option><option value="unelevated">兼容隔离</option></select></div><p class="setting-muted">{{mode==='elevated'?'需要系统管理员授权。':'无需管理员，网络限制较弱。'}}</p><UiButton v-if="state?.readiness!=='ready'||state?.mode!==mode" icon="check" :disabled="busy||!desktop" @click="run(true)">应用</UiButton><p v-if="error" role="alert">{{error}} <UiButton icon="refresh" :disabled="busy||!desktop" @click="run()">重试</UiButton></p></div></section></template>
