<script setup lang="ts">
import UiButton from './UiButton.vue';
import {ref,computed} from 'vue';
const props=defineProps<{request:any;busy:boolean}>();const emit=defineEmits<{answer:[answers:Record<string,string[]>]}>();
const choices=ref<Record<string,string>>(Object.create(null)),free=ref<Record<string,string>>(Object.create(null));
const text=(q:any)=>!q.options?.length||choices.value[q.id]==='__other__'?free.value[q.id]??'':choices.value[q.id]??'';
const ready=computed(()=>props.request.params.questions.every((q:any)=>text(q).trim()));
function submit(skip=false){emit('answer',Object.fromEntries(props.request.params.questions.map((q:any)=>[q.id,skip?[]:[text(q)]])))}
</script>
<template><form class="native-question" @submit.prevent="submit()"><strong>Codex 提问</strong><fieldset v-for="q in request.params.questions" :key="q.id" :disabled="busy"><legend>{{q.header}}</legend><p>{{q.question}}</p><template v-if="q.options?.length"><label v-for="o in q.options" :key="o.label"><input v-model="choices[q.id]" type="radio" :name="request.id+'-'+q.id" :value="o.label">{{o.label}}<small>{{o.description}}</small></label><label v-if="q.isOther"><input v-model="choices[q.id]" type="radio" :name="request.id+'-'+q.id" value="__other__">自行填写</label></template><input v-if="!q.options?.length||choices[q.id]==='__other__'" v-model="free[q.id]" :type="q.isSecret?'password':'text'" :aria-label="q.question" maxlength="20000" autocomplete="off"></fieldset><div><UiButton icon="check" class="primary" :disabled="busy||!ready">提交回答</UiButton><UiButton icon="chevron" type="button" :disabled="busy" @click="submit(true)">跳过</UiButton></div></form></template>
<style scoped>.native-question{border-left:2px solid var(--accent);padding:12px!important;margin:12px 0}.native-question fieldset{border:0;margin:12px 0;padding:0;min-width:0}.native-question legend{color:var(--muted);font-size:0.923077rem}.native-question p{font-size:1.0rem;line-height:1.6}.native-question label{display:grid;grid-template-columns:16px minmax(0,1fr);column-gap:6px;font-size:1.0rem;margin:10px 0;line-height:1.5}.native-question small{display:block;color:var(--muted);grid-column:2;margin-left:0}.native-question input[type=radio]{width:auto;margin:3px 0;align-self:start}.native-question input:not([type=radio]){width:100%;box-sizing:border-box}.native-question>div{display:flex;gap:8px}</style>
