<script setup lang="ts">
import {useStockData} from './use-stock-data';
import UiButton from './UiButton.vue';
import {ref,watch,computed,onBeforeUnmount} from 'vue';
import {syncDateRange} from './date-range.mjs';
import type {FinancialData,FinancialVersion} from '../../../../packages/contracts/desktop';
const props=defineProps<{instrumentId:string;start:string;end:string;category?:'financial'|'valuation'}>();
const selected=ref(''),versions=ref<FinancialVersion[]>([]);const endpoint=ref(props.category==='valuation'?'daily_basic':'income'),data=ref<FinancialData>({manifest:null,items:[]}),busy=ref(false),error=ref(''),loading=ref(false);
const desktop=Boolean(window.stock);let closed=false;
const fields:Record<string,[string,string][]>= {income:[['revenue','营业收入'],['n_income_attr_p','归母净利润']],balancesheet:[['total_assets','总资产'],['total_liab','总负债']],cashflow:[['n_cashflow_act','经营现金流净额']],daily_basic:[['close','收盘价'],['pe','PE'],['pe_ttm','PE TTM'],['pb','PB'],['total_mv','总市值'],['circ_mv','流通市值']]};
const selectedVersion=computed(()=>versions.value.find(item=>item.snapshotId===data.value.manifest?.id));const columns=computed(()=>fields[endpoint.value]);let version=0;
onBeforeUnmount(()=>{closed=true;++version});
const historical=computed(()=>Boolean(data.value.manifest&&versions.value.length&&data.value.manifest.id!==versions.value[0].snapshotId));
async function load(refresh=true){if(!window.stock||closed)return;const id=++version;loading.value=true;error.value='';try{if(refresh){selected.value='';versions.value=[];const list=await window.stock.financialSnapshots(props.instrumentId,endpoint.value);if(id!==version)return;versions.value=list}const next=await window.stock.readFinancials(props.instrumentId,endpoint.value,selected.value||undefined);if(id===version)data.value=next}catch(e){if(id===version)error.value=String(e instanceof Error?e.message:e)}finally{if(id===version)loading.value=false}}
watch(()=>[props.instrumentId,endpoint.value],()=>{data.value={manifest:null,items:[]};void load()},{immediate:true});
async function sync(){if(!window.stock||busy.value||closed)return;const code=props.instrumentId,api=endpoint.value;busy.value=true;error.value='';try{const range=syncDateRange(props.start,props.end);await window.stock.syncFinancials(code,api,range.start,range.end);if(!closed&&code===props.instrumentId&&api===endpoint.value)await load()}catch(e){if(!closed&&code===props.instrumentId&&api===endpoint.value)error.value=String(e instanceof Error?e.message:e)}finally{if(!closed)busy.value=false}}
const format=(value:unknown)=>typeof value==='number'?value.toLocaleString('zh-CN',{maximumFractionDigits:2}):'—';
const displayRows=computed<Record<string,unknown>[]>(()=>data.value.items.map(row=>({...row})));
const yoy=(row:Record<string,unknown>,key:string)=>{const values=row.yoy as Record<string,unknown>|undefined;return typeof values?.[key]==='number'?format(values[key])+'%':'—'};
const automatic=useStockData(()=>({instrumentId:props.instrumentId,endpoint:endpoint.value as 'income'|'balancesheet'|'cashflow'|'daily_basic',years:3}),async()=>{if(!window.stock||selected.value||closed)return;const list=await window.stock.financialSnapshots(props.instrumentId,endpoint.value);if(list[0]?.snapshotId!==data.value.manifest?.id)await load()});
</script>
<template><section class="financial-panel"><p v-if="automatic.state.value==='updating'" class="financial-note" role="status">{{data.manifest?'正在检查更新…':'正在获取资料…'}}</p><p v-if="automatic.state.value==='failed'" class="financial-note" role="alert">{{automatic.message.value}} <UiButton icon="refresh" @click="automatic.retry">重试</UiButton></p><div class="financial-controls"><h2>{{category==='valuation'?'估值':category==='financial'?'财务':'财务与估值'}}</h2><label>报表 <select v-model="endpoint" :disabled="busy"><option v-if="category!=='valuation'" value="income">利润表</option><option v-if="category!=='valuation'" value="balancesheet">资产负债表</option><option v-if="category!=='valuation'" value="cashflow">现金流量表</option><option v-if="!category||category==='valuation'" value="daily_basic">每日估值</option></select></label><label v-if="versions.length">版本（最近 100 个） <select v-model="selected" :disabled="busy||loading" @change="load(false)"><option value="">最新保存版本</option><option v-for="item in versions" :key="item.snapshotId" :value="item.snapshotId">{{new Date(item.collectedAt).toLocaleString('zh-CN')}} · {{item.snapshotId.slice(0,8)}} · 截至 {{item.asOf}}</option></select></label><UiButton icon="refresh" :disabled="!desktop||busy||loading" @click="sync">{{busy?'正在同步…':'同步当前报表'}}</UiButton></div><p class="financial-note">使用上方日期范围：财报按公告日请求，估值按交易日请求。金额单位：元；PE/PB：倍。利润与现金流为年初至报告期累计，资产负债为期末余额。</p><p v-if="error" class="banner error" role="alert">{{error}}</p><p v-if="loading" class="financial-note" role="status">正在读取报表快照…</p><p v-else-if="!data.manifest&&!error" class="financial-note">尚无此报表数据。同步前请确认账号接口权限。</p><template v-if="data.manifest"><p v-if="historical" class="banner" role="status">正在查看较早保存的报表版本；可切换至最新保存版本。保存时间不等于披露时间。</p><p class="financial-note">Tushare · {{endpoint==='daily_basic'?'交易日截至':'披露日截至'}} {{data.manifest.asOf}} · 保存于 {{new Date(data.manifest.collectedAt).toLocaleString('zh-CN')}} · 快照 {{data.manifest.id.slice(0,16)}} <span v-if="selectedVersion"> · 请求范围 {{selectedVersion.start}}–{{selectedVersion.end}}</span> · 显示最新 {{data.items.length}} / {{data.manifest.rows}} 条</p><div class="financial-table"><table><thead><tr><th>{{endpoint==='daily_basic'?'交易日':'报告期 / 披露日'}}</th><th v-for="[key,label] in columns" :key="key" class="numeric">{{label}}<small v-if="endpoint!=='daily_basic'">金额 / 同比</small></th></tr></thead><tbody><tr v-for="(row,index) in displayRows" :key="index"><td>{{row.trade_date??row.end_date}}<template v-if="endpoint!=='daily_basic'"><small>公告 {{row.ann_date}}<br>实际公告 {{row.f_ann_date??'—'}}</small><small v-if="Number(row.revisionCount)>1">同报告期存在 {{row.revisionCount}} 条记录</small></template></td><td v-for="[key] in columns" :key="key" class="numeric">{{format(row[key])}}<small v-if="endpoint!=='daily_basic'">{{yoy(row,key)}}</small></td></tr></tbody></table></div></template><p class="financial-note">“—”表示缺失或不可比，不按零处理。同口径去年同期且基数为正、修订唯一时才计算同比。本数据不支持严格时点回测，历史修订可能不完整。</p></section></template>
<style scoped>.financial-panel{border-top:1px solid var(--line);padding:24px 0;margin-top:18px}.financial-controls{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:0 24px}.financial-controls h2{flex:1 0 auto;white-space:nowrap}.financial-note{font-size:0.923077rem;color:var(--muted);margin:14px 24px}.financial-table{overflow:auto;max-height:480px}table{min-width:540px}small{display:block;color:var(--muted);font-size:0.846154rem;line-height:1.6;margin-top:5px}td{vertical-align:top}</style>
