<script setup lang="ts">
import UiButton from './UiButton.vue';
import type {Holding,HoldingsSummary,HoldingValuation} from '../../../../packages/contracts/generated';
defineProps<{summary:HoldingsSummary|null,busy:boolean}>();
defineEmits<{edit:[holding:Holding],open:[id:string]}>();
function format(value:string|null|undefined){if(value==null)return '—';const [whole,part='']=value.split('.');return whole.replace(/\B(?=(\d{3})+(?!\d))/g,',')+'.'+part.padEnd(2,'0')}
function reason(row:HoldingValuation){return {closed:'已清仓',missingPrice:'缺少行情',priceBeforeHolding:'价格早于持仓日期',dataError:'行情校验失败',valued:''}[row.status]}
</script>
<template><section v-if="summary" class="valuation" aria-label="持仓估值">
  <div class="totals"><div><small>持仓市值（元）</small><strong>{{format(summary.marketValue)}}</strong></div><div><small>持仓成本</small><strong>{{format(summary.costBasis)}}</strong></div><div><small>浮动盈亏</small><strong>{{format(summary.floatingProfit)}}</strong></div><div><small>已实现盈亏</small><strong>{{format(summary.realizedProfit)}}</strong></div></div>
  <p class="valuation-date">{{summary.priceDates.length>1?'混合收盘日期：'+summary.priceDates[0]+' — '+summary.priceDates.at(-1):summary.priceDates.length?'收盘日期 '+summary.priceDates[0]:'暂无有效收盘报价'}} · 手动持仓 · 不含现金</p>
  <p v-if="summary.missingPriceCount||summary.unknownCostCount||summary.unknownRealizedCount" class="coverage">{{summary.missingPriceCount}} 项缺少有效报价，{{summary.unknownCostCount}} 项成本未知，{{summary.unknownRealizedCount}} 项历史收益未知。已估值 {{format(summary.pricedMarketValue)}} 元 · 已知成本 {{format(summary.knownCostBasis)}} 元 · 已知已实现盈亏 {{format(summary.knownRealizedProfit)}} 元</p>
  <details class="industry-distribution"><summary>行业分布 <span>申万 2021 · 当前成分</span></summary><p v-if="summary.industryStatus!=='ready'">{{summary.industryStatus==='error'?'行业资料校验失败':'尚无行业资料'}}，暂列未分类。</p><p>占比以已估值持仓市值为分母，不含现金与缺报价部分。{{summary.industryCollectedAt?'成分采集于 '+summary.industryCollectedAt.slice(0,10):''}}</p><div v-for="group in summary.industries" :key="group.id??'unknown'" class="industry-weight"><span>{{group.name}}</span><meter min="0" max="100" :value="Number(group.pricedHoldingsPercent??0)" :aria-label="group.name+'已估值占比'"></meter><span>{{group.pricedHoldingsPercent===null?'—':group.pricedHoldingsPercent+'%'}}</span><span>{{format(group.marketValue)}} 元</span><small>{{group.holdingCount}} 只{{group.missingPriceCount?' · '+group.missingPriceCount+' 只缺报价':''}}</small></div><p v-if="!summary.industries.length">暂无在持仓股票</p></details>
  <div class="table-scroll"><table><thead><tr><th>股票 / 持仓日期</th><th>股数 / 成本价</th><th>收盘价 / 日期</th><th>市值（元）</th><th>持仓成本 / 已实现盈亏</th><th>浮动盈亏（元）</th><th>已估值占比</th><th/></tr></thead><tbody>
    <tr v-for="row in summary.items" :key="row.holding.instrumentId"><td><UiButton icon="chevron" @click="$emit('open',row.holding.instrumentId)">{{row.holding.name}}</UiButton><small>{{row.holding.instrumentId}} · {{row.holding.asOf}}</small></td><td>{{row.holding.quantity}}<small>{{row.holding.costPrice===null?'成本未知':format(row.holding.costPrice)+' 元'}}</small></td><td>{{format(row.price)}}<small>{{row.priceDate??'无行情'}}{{row.provider?' · Tushare':''}}</small><small v-if="reason(row)">{{reason(row)}}</small></td><td>{{format(row.marketValue)}}</td><td>{{format(row.costBasis)}}<small>已实现 {{format(row.realizedProfit)}}</small></td><td>{{format(row.floatingProfit)}}<small v-if="row.profitPercent!==null">{{row.profitPercent}}%</small></td><td>{{row.pricedHoldingsPercent===null?'—':row.pricedHoldingsPercent+'%'}}</td><td><UiButton icon="edit" icon-only :disabled="busy" @click="$emit('edit',row.holding)">编辑</UiButton></td></tr>
  </tbody></table></div>
</section></template>
<style scoped>
.totals{display:flex;flex-wrap:wrap;gap:28px;padding:12px 0 18px;border-bottom:1px solid var(--line)}.totals div{display:grid;gap:6px}.totals strong{font-size:1.692308rem;font-variant-numeric:tabular-nums}.valuation p,.valuation small{color:var(--muted)}.valuation p{line-height:1.6;font-size:0.923077rem}.table-scroll{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px 8px;border-bottom:1px solid var(--line);font-variant-numeric:tabular-nums;white-space:nowrap}td small{display:block;margin-top:4px;font-size:0.846154rem}
.industry-distribution{margin:12px 0 18px}.industry-distribution summary{cursor:pointer;font-size:13px}.industry-distribution summary span{margin-left:12px;color:var(--muted);font-size:12px}.industry-weight{display:grid;grid-template-columns:90px minmax(60px,1fr) 65px 110px 130px;gap:12px;align-items:center;font-size:12px;padding:7px 0}.industry-weight meter{width:100%;height:7px;accent-color:var(--accent)}.industry-weight meter::-webkit-meter-bar{background:var(--line);border:0}.industry-weight meter::-webkit-meter-optimum-value{background:var(--accent)}@media(max-width:900px){.industry-weight{grid-template-columns:70px minmax(40px,1fr) 55px}.industry-weight>span:nth-of-type(3),.industry-weight>small{grid-column:auto}.totals{gap:18px}}
</style>
