<script setup lang="ts">
import UiButton from './UiButton.vue';
import {ref,watch,onBeforeUnmount} from 'vue';
import type {MarketId,MarketSnapshot} from '../../../../packages/contracts/generated';
const indices:[MarketId,string][]=[['SH_A','沪市 A 股'],['SZ_A','深市 A 股'],['SH_STAR','科创板'],['SZ_GEM','创业板'],['SZ_STOCK','深圳股票（含 A/B 股）']];
const selected=ref<MarketId>('SH_A'),data=ref<MarketSnapshot|null>(null),error=ref(''),loading=ref(false),syncing=ref(false);let request=0,closed=false;
const date=(value:Date)=>`${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,'0')}-${String(value.getDate()).padStart(2,'0')}`;
const end=ref(date(new Date())),start=ref(date(new Date(Date.now()-45*86400000)));
const number=(value:number|null)=>value===null?'—':value.toLocaleString('zh-CN',{maximumFractionDigits:2});
async function read(){const id=++request;data.value=null;error.value='';loading.value=true;try{const result=await window.stock?.readMarket(selected.value);if(id===request&&!closed)data.value=result??null}catch(e){if(id===request)error.value=e instanceof Error?e.message:String(e)}finally{if(id===request)loading.value=false}}
async function sync(){if(!window.stock||syncing.value)return;const code=selected.value;syncing.value=true;error.value='';try{if(!/^\d{4}-\d{2}-\d{2}$/.test(start.value)||!/^\d{4}-\d{2}-\d{2}$/.test(end.value)||start.value>end.value)throw Error('请选择有效日期范围。');await window.stock.syncMarket(code,start.value.replaceAll('-',''),end.value.replaceAll('-',''));if(!closed&&selected.value===code)await read()}catch(e){if(!closed)error.value=e instanceof Error?e.message:String(e)}finally{syncing.value=false}}
watch(selected,read,{immediate:true});onBeforeUnmount(()=>{closed=true;++request});
</script>
<template><section class="market-statistics" aria-label="市场交易统计"><header><h2>市场交易统计</h2><select v-model="selected" aria-label="选择市场" :disabled="syncing"><option v-for="[id,name] in indices" :key="id" :value="id">{{name}}</option></select><UiButton icon="refresh" icon-only :disabled="loading||syncing" @click="read">刷新本地</UiButton></header>
<p class="hint">交易所板块口径，范围可能重叠，不加总；不含北交所。</p>
<p v-if="error" role="alert">{{error}}</p><p v-if="loading" role="status">正在读取市场快照…</p>
<template v-else-if="data"><div class="summary"><strong>{{number(data.items.at(-1)!.amount===null?null:data.items.at(-1)!.amount!/1e8)}} <small>亿元成交额</small></strong><span>挂牌数量 {{number(data.items.at(-1)!.com_count)}}</span><span>总市值 {{number(data.items.at(-1)!.total_mv===null?null:data.items.at(-1)!.total_mv!/1e8)}} 亿元</span></div><p class="hint">{{data.name}} · Tushare / {{data.endpoint}} · 截至 {{data.asOf}} · 保存于 {{new Date(data.collectedAt).toLocaleString()}}</p>
<details><summary>历史统计 · 最近 60 条</summary><div class="table-scroll"><table><thead><tr><th>交易日</th><th>成交额（亿元）</th><th>成交量（亿股）</th><th>挂牌数量</th><th>总市值（亿元）</th><th>平均市盈率</th><th>换手率（%）</th></tr></thead><tbody><tr v-for="row in data.items.slice(-60).reverse()" :key="row.date"><td>{{row.date}}</td><td>{{number(row.amount===null?null:row.amount/1e8)}}</td><td>{{number(row.vol===null?null:row.vol/1e8)}}</td><td>{{number(row.com_count)}}</td><td>{{number(row.total_mv===null?null:row.total_mv/1e8)}}</td><td>{{number(row.pe)}}</td><td>{{number(row.tr)}}</td></tr></tbody></table></div></details></template>
<p v-else class="hint">尚无这个市场范围的本地快照，可使用已配置的数据源同步。</p>
<details><summary>同步市场交易统计</summary><div class="controls"><label>开始 <input v-model="start" type="date" :disabled="syncing"></label><label>结束 <input v-model="end" type="date" :disabled="syncing"></label><UiButton icon="refresh" :disabled="syncing||loading" @click="sync">{{syncing?'正在同步…':'同步市场'}}</UiButton></div></details></section></template>
<style scoped>.market-statistics{margin:18px 24px;padding-bottom:18px;border-bottom:1px solid var(--line);min-width:0}.market-statistics header,.summary,.controls{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.market-statistics h2{margin:0;font-size:1.230769rem}.market-statistics .hint{font-size:0.923077rem;line-height:1.7;color:var(--muted)}.summary strong{font-size:1.846154rem;font-variant-numeric:tabular-nums}.summary small{font-size:0.923077rem;font-weight:400}.market-statistics details{margin-top:12px}.market-statistics summary{cursor:pointer;color:var(--muted)}.controls{margin-top:12px}.controls input{max-width:145px}.table-scroll{overflow:auto;max-height:320px}.table-scroll table{white-space:nowrap;width:100%}[role=alert]{color:var(--danger)}</style>
