<script setup lang="ts">
import {ref,computed} from 'vue';
import UiButton from './UiButton.vue';
import SectorList from './SectorList.vue';
import {useMarket,marketIndices,marketNumber as fmt} from './use-market';
const props=defineProps<{colorMode:string;indexId?:string}>();const emit=defineEmits<{open:[id:string];index:[id:string];sector:[id:string,name:string];changed:[]}>();
const {breadth,indices,error,updating,refresh}=useMarket();const sort=ref('amount'),query=ref(''),exchange=ref(''),adding=ref(''),notice=ref(''),page=ref(1);
const filtered=computed(()=>[...(breadth.value?.items??[])].filter(r=>(!exchange.value||r.instrumentId.endsWith(exchange.value))&&(!query.value||`${r.name} ${r.instrumentId}`.toLowerCase().includes(query.value.toLowerCase()))).sort((a,b)=>sort.value==='amount'?b.amount-a.amount:sort.value==='down'?a.pct-b.pct:b.pct-a.pct));
const counts=computed(()=>{const a=breadth.value?.items??[];return {up:a.filter(r=>r.pct>0).length,down:a.filter(r=>r.pct<0).length,flat:a.filter(r=>r.pct===0).length,limitUp:a.filter(r=>r.limitUp).length,limitDown:a.filter(r=>r.limitDown).length,amount:a.reduce((s,r)=>s+r.amount,0)}});
const tone=(n:number|null|undefined)=>n==null||n===0?'':((n>0)===(props.colorMode==='red-up')?'rise':'fall');
const selected=computed(()=>indices.value[props.indexId??'000001.SH']);
const points=computed(()=>{const a=selected.value?.items??[];if(a.length<2)return '';const min=Math.min(...a.map(r=>r.close)),max=Math.max(...a.map(r=>r.close));return a.map((r,i)=>`${i/(a.length-1)*1000},${180-(r.close-min)/(max-min||1)*160}`).join(' ')});
async function add(id:string){if(adding.value)return;adding.value=id;notice.value='';try{const api=window.stock!,groups=await api.watchlists();let group=groups.find(g=>g.name==='默认自选')??(groups.length===1?groups[0]:null);if(!group)group=await api.createWatchlist('默认自选');await api.addWatchlistMember(group.id,id);notice.value='已加入自选';emit('changed')}catch(e){notice.value=String(e)}finally{adding.value=''}}
</script>
<template><div class="market-surface"><section class="market-home"><header><h2>{{indexId?marketIndices.find(i=>i[0]===indexId)?.[1]:'市场总览'}}</h2><span>{{breadth?'收盘 · '+breadth.asOf:'收盘数据 · Tushare'}}</span><UiButton icon="refresh" icon-only :disabled="updating" @click="refresh(true)">刷新行情</UiButton></header><p v-if="updating||error" class="market-message" role="status">{{updating?'正在更新行情… ':''}}{{error}}</p>
<div class="index-strip"><button v-for="[id,name] in marketIndices" :key="id" @click="emit('index',id)"><span>{{name}}</span><strong>{{fmt(indices[id]?.items.at(-1)?.close)}}</strong><small :class="tone(indices[id]?.items.at(-1)?.pct_chg)">{{indices[id]?.items.at(-1)?.pct_chg==null?'—':fmt(indices[id]?.items.at(-1)?.pct_chg)+'%'}}</small><small>{{indices[id]?.asOf??'暂无快照'}}</small></button></div>
<section class="index-chart"><div><h3>{{selected?.name??'上证指数'}} · 收盘走势</h3><small v-if="selected">{{selected.items[0]?.date}} — {{selected.asOf}}</small></div><svg v-if="points" viewBox="0 0 1000 200" preserveAspectRatio="none" role="img" :aria-label="`${selected?.name}收盘走势`"><polyline :points="points" fill="none" stroke="var(--accent)" stroke-width="1.5" vector-effect="non-scaling-stroke"/></svg><p v-else class="market-message">{{updating?'正在获取指数日线…':'暂无指数日线'}}</p><details v-if="indexId&&selected"><summary>每日行情</summary><div class="table-scroll"><table><thead><tr><th>日期</th><th>收盘</th><th>涨跌幅</th><th>成交额（亿元）</th></tr></thead><tbody><tr v-for="r in [...selected.items].reverse()" :key="r.date"><td>{{r.date}}</td><td>{{fmt(r.close)}}</td><td :class="tone(r.pct_chg)">{{fmt(r.pct_chg)}}%</td><td>{{r.amount==null?'—':fmt(r.amount/1e8)}}</td></tr></tbody></table></div></details></section>
<template v-if="!indexId"><section class="market-width"><h3>市场宽度 <small v-if="breadth">{{breadth.items.length}} 只当日有行情的股票</small></h3><div class="width-values"><span>上涨<strong :class="tone(1)">{{breadth?counts.up:'—'}}</strong></span><span>下跌<strong :class="tone(-1)">{{breadth?counts.down:'—'}}</strong></span><span>平盘<strong>{{breadth?counts.flat:'—'}}</strong></span><span>涨停<strong :class="tone(1)">{{breadth?.limitsAvailable?counts.limitUp:'—'}}</strong></span><span>跌停<strong :class="tone(-1)">{{breadth?.limitsAvailable?counts.limitDown:'—'}}</strong></span><span>成交额（亿）<strong>{{breadth?fmt(counts.amount/1e8):'—'}}</strong></span></div><div v-if="breadth" class="width-bar" aria-hidden="true"><i :class="tone(1)" :style="{flex:counts.up}"/><i :style="{flex:counts.flat}"/><i :class="tone(-1)" :style="{flex:counts.down}"/></div><small v-if="breadth&&!breadth.limitsAvailable">涨跌停价格资料不完整</small></section>
<SectorList summary :color-mode="colorMode" @open="(id,name)=>emit('sector',id,name)"/><section class="rankings"><div class="ranking-toolbar"><h3>个股排行</h3><select v-model="sort" aria-label="排行排序" @change="page=1"><option value="amount">成交额</option><option value="up">涨幅</option><option value="down">跌幅</option></select><select v-model="exchange" aria-label="交易所筛选" @change="page=1"><option value="">全部交易所</option><option value=".SH">沪市</option><option value=".SZ">深市</option><option value=".BJ">北交所</option></select><input v-model="query" placeholder="筛选名称或代码" aria-label="筛选排行" @input="page=1"/></div><p v-if="notice" role="status" class="market-message">{{notice}}</p><div class="table-scroll"><table><thead><tr><th>股票</th><th>收盘价</th><th>涨跌幅</th><th>成交额（亿元）</th><th>自选</th></tr></thead><tbody><tr v-for="r in filtered.slice((page-1)*50,page*50)" :key="r.instrumentId"><td><button class="stock-link" @click="emit('open',r.instrumentId)">{{r.name}}<small>{{r.instrumentId}}</small></button></td><td>{{fmt(r.close)}}</td><td :class="tone(r.pct)">{{fmt(r.pct)}}%</td><td>{{fmt(r.amount/1e8)}}</td><td><UiButton icon="star" icon-only :disabled="!!adding" @click="add(r.instrumentId)">加入自选 {{r.name}}</UiButton></td></tr></tbody></table></div><p v-if="!filtered.length" class="market-message">{{breadth?'没有符合条件的股票':updating?'正在获取市场行情…':'尚无市场行情，可点击刷新。'}}</p><div v-if="filtered.length>50" class="pagination"><UiButton icon="chevron" :disabled="page<=1" @click="page--">上一页</UiButton><span>{{page}} / {{Math.ceil(filtered.length/50)}}</span><UiButton icon="chevron" :disabled="page*50>=filtered.length" @click="page++">下一页</UiButton></div></section></template>
</section></div></template>
<style scoped>
.market-surface{container-type:inline-size}.market-home{padding:18px 24px;max-width:1400px;margin:0 auto;min-width:0}.market-home header{display:flex;align-items:center;gap:12px}.market-home h2{font-size:18px;margin:0 auto 0 0}.market-home h3{font-size:13px;font-weight:500;margin:0}.market-home small,.market-home header>span{color:var(--muted);font-size:11px;font-weight:400}.index-strip{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));margin-top:20px;border-bottom:1px solid var(--line);padding-bottom:18px;gap:12px}.index-strip button{display:flex;flex-direction:column;align-items:flex-start;gap:6px;padding:8px;text-align:left;min-width:0}.index-strip strong{font-size:20px;font-weight:500;font-variant-numeric:tabular-nums}.index-strip span{font-size:12px}.index-chart{padding:20px 0;border-bottom:1px solid var(--line)}.index-chart>div:first-child{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap}.index-chart svg{width:100%;height:170px;margin-top:14px}.index-chart details{margin-top:12px}.index-chart summary{font-size:12px;color:var(--muted);cursor:pointer}.market-width{padding:20px 0;border-bottom:1px solid var(--line)}.market-width h3 small{margin-left:8px}.width-values{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin:18px 0}.width-values>span{font-size:11px;color:var(--muted)}.width-values strong{display:block;font-size:18px;font-weight:500;color:var(--text);margin-top:8px;font-variant-numeric:tabular-nums}.width-bar{display:flex;gap:2px;height:3px}.width-bar i{background:var(--muted)}.width-bar i.rise{background:#ee8585}.width-bar i.fall{background:#64bca0}.rankings{padding:20px 0}.ranking-toolbar{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-bottom:12px}.ranking-toolbar h3{margin-right:auto}.ranking-toolbar input{width:145px;min-width:0}.ranking-toolbar input,.ranking-toolbar select{min-height:28px;padding:4px 6px;font-size:12px}.table-scroll{overflow:auto;max-height:500px}table{width:100%;margin:0;white-space:nowrap;font-variant-numeric:tabular-nums;font-size:12px}th{color:var(--muted);font-weight:400}td,th{text-align:right;padding:8px}td:first-child,th:first-child{text-align:left}.stock-link{text-align:left;padding:0}.stock-link small{display:block;margin-top:3px}.market-message{color:var(--muted);font-size:12px;overflow-wrap:anywhere}.pagination{display:flex;justify-content:flex-end;align-items:center;gap:8px;font-size:12px;margin-top:10px}.rise{color:#ee8585!important}.fall{color:#64bca0!important}@container (max-width:650px){.market-surface{container-type:inline-size}.market-home{padding:14px}.index-strip{grid-template-columns:repeat(2,minmax(0,1fr))}.width-values{grid-template-columns:repeat(3,1fr)}}@media(max-width:800px){.index-strip{grid-template-columns:repeat(2,minmax(0,1fr))}.width-values{grid-template-columns:repeat(3,1fr)}}
</style>
