<script setup lang="ts">
import {ref,computed,watch,onBeforeUnmount} from 'vue';
import UiButton from './UiButton.vue';
import SectorList from './SectorList.vue';
import {useMarket,marketIndices,marketNumber as fmt} from './use-market';
import type {Instrument} from '../../../../packages/contracts/generated';
const props=defineProps<{colorMode:string}>();const emit=defineEmits<{open:[id:string];overview:[];index:[id:string];sector:[id:string,name:string]}>();
const {breadth,indices,error,updating,refresh}=useMarket();const tab=ref('indices'),sort=ref('up'),query=ref(''),matches=ref<Instrument[]>([]),searchError=ref('');let generation=0,timer:ReturnType<typeof setTimeout>;
watch(query,()=>{const id=++generation;clearTimeout(timer);matches.value=[];searchError.value='';if(!query.value.trim())return;timer=setTimeout(async()=>{try{const r=await window.stock!.searchInstruments(query.value.trim(),0);if(id===generation)matches.value=r.items}catch(e){if(id===generation)searchError.value=String(e)}},180)});onBeforeUnmount(()=>{generation++;clearTimeout(timer)});
const rows=computed(()=>[...(breadth.value?.items??[])].sort((a,b)=>sort.value==='amount'?b.amount-a.amount:sort.value==='down'?a.pct-b.pct:b.pct-a.pct).slice(0,50));
const tone=(n:number|null|undefined)=>n==null||n===0?'':((n>0)===(props.colorMode==='red-up')?'rise':'fall');
</script>
<template><section class="market-browser"><input v-model="query" placeholder="搜索股票名称或代码" aria-label="市场搜索"/><div v-if="query.trim()" class="market-list"><p v-if="searchError" role="alert">{{searchError}}</p><button v-for="i in matches" :key="i.id" @click="emit('open',i.id)"><span>{{i.name}}<small>{{i.id}}</small></span></button><p v-if="!matches.length&&!searchError">没有匹配股票</p></div><template v-else><div class="market-switch" role="tablist" aria-label="市场分类"><button role="tab" :aria-selected="tab==='indices'" @click="tab='indices'">大盘</button><button role="tab" :aria-selected="tab==='sectors'" @click="tab='sectors'">板块</button><button role="tab" :aria-selected="tab==='stocks'" @click="tab='stocks'">个股</button><UiButton v-if="tab!=='sectors'" icon="refresh" icon-only :disabled="updating" @click="refresh(true)">刷新市场</UiButton></div><div class="market-list"><template v-if="tab==='indices'"><button class="overview-link" @click="emit('overview')">市场总览 <span>→</span></button><button v-for="[id,name] in marketIndices" :key="id" @click="emit('index',id)"><span>{{name}}<small>{{id}}</small></span><span class="numbers">{{fmt(indices[id]?.items.at(-1)?.close)}}<small :class="tone(indices[id]?.items.at(-1)?.pct_chg)">{{indices[id]?.items.at(-1)?.pct_chg==null?'—':fmt(indices[id]?.items.at(-1)?.pct_chg)+'%'}}</small></span></button></template><SectorList v-else-if="tab==='sectors'" :color-mode="colorMode" @open="(id,name)=>emit('sector',id,name)"/><template v-else><select v-model="sort" aria-label="个股排行"><option value="up">涨幅排行</option><option value="down">跌幅排行</option><option value="amount">成交额排行</option></select><button v-for="r in rows" :key="r.instrumentId" @click="emit('open',r.instrumentId)"><span>{{r.name}}<small>{{r.instrumentId}}</small></span><span :class="sort==='amount'?'':tone(r.pct)">{{sort==='amount'?fmt(r.amount/1e8)+' 亿':fmt(r.pct)+'%'}}</span></button><p v-if="!rows.length">{{updating?'正在获取市场行情…':'尚无市场快照'}}</p></template></div><footer v-if="tab!=='sectors'"><span v-if="updating" role="status">正在更新 · </span>{{breadth?'收盘 · '+breadth.asOf:'收盘数据'}}<p v-if="error" role="status">{{error}}</p></footer></template></section></template>
<style scoped>
.market-browser{display:flex;flex-direction:column;min-height:0;flex:1}.market-browser>input{margin:8px;width:calc(100% - 16px);padding:5px 8px;min-height:28px}.market-switch{display:flex;align-items:center;border-bottom:1px solid var(--line);height:34px;padding:0 6px;gap:4px}.market-switch button{height:28px;padding:4px 8px}.market-switch [aria-selected=true]{color:var(--accent)}.market-switch>.ui-icon-only{margin-left:auto}.market-list{overflow:auto;flex:1}.market-list>button{display:flex;width:100%;align-items:center;justify-content:space-between;text-align:left;padding:9px 12px;gap:8px;border-radius:0;font-size:13px}.market-list>button:hover{background:var(--raised)!important}.market-list small{display:block;color:var(--muted);font-size:11px;margin-top:3px}.numbers{text-align:right;font-variant-numeric:tabular-nums}.market-list select{margin:8px;width:calc(100% - 16px);min-height:28px}.market-browser p,.market-browser footer{padding:8px 12px;color:var(--muted);font-size:12px}.market-browser footer p{padding:0;margin-bottom:0;overflow-wrap:anywhere}.rise{color:#ee8585!important}.fall{color:#64bca0!important}.overview-link{color:var(--accent);border-bottom:1px solid var(--line)!important}
</style>
