<script setup lang="ts">
import {computed,onMounted,onBeforeUnmount,ref,watch} from 'vue';
import UiButton from './UiButton.vue';
import {connectionError} from './connection-error';
import {createRefreshQueue} from './refresh-queue.mjs';
import type {Instrument,Watchlist,Holding,HoldingsSummary,LatestQuote} from '../../../../packages/contracts/generated';
const props=defineProps<{colorMode:string;project:string}>(),emit=defineEmits<{open:[id:string];changed:[]}>(),api=window.stock;
const tab=ref<'watch'|'hold'>('watch'),groups=ref<Watchlist[]>([]),members=ref<Record<string,Instrument[]>>({}),quotes=ref<Record<string,LatestQuote>>({}),changes=ref<Record<string,number|null>>({}),summary=ref<HoldingsSummary|null>(null),collapsed=ref<string[]>([]),filter=ref(''),showSearch=ref(false),adding=ref(false),query=ref(''),matches=ref<Instrument[]>([]),targetGroup=ref(''),busy=ref(false),loading=ref(false),error=ref(''),selected=ref(''),groupName=ref(''),newGroup=ref(false);
const edit=ref<{instrumentId:string;name:string;quantity:number;costPrice:string;asOf:string;revision:number}|null>(null),menu=ref<{id:string;group:string;x:number;y:number}|null>(null);let timer:ReturnType<typeof setInterval>,searchTimer:ReturnType<typeof setTimeout>,closed=false,searchVersion=0;const versions=new Map<string,string>();const prepared=new Map<string,number>();
const activeHoldings=computed(()=>summary.value?.items.filter(r=>r.holding.quantity>0)??[]);
const visibleGroups=computed(()=>groups.value.map(g=>({...g,rows:(members.value[g.id]??[]).filter(match)})));
const flat=computed(()=>Array.from(new Map(Object.values(members.value).flat().filter(match).map(r=>[r.id,r])).values()));
function match(i:{name:string;id?:string;instrumentId?:string}){return (i.name+' '+(i.id??i.instrumentId)).toLowerCase().includes(filter.value.toLowerCase())}
function fmt(v:unknown){return v==null?'—':Number(v).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}
function tone(v:unknown){if(v==null||!Number(v))return '';return (Number(v)>0)===(props.colorMode!=='green-up')?'rise':'fall'}
const refresh=createRefreshQueue(load);
const dataError=ref('');const dataFailures=new Map<string,string>();
async function load(){if(!api||loading.value||closed)return;loading.value=true;try{const [gs,hs]=await Promise.all([api.watchlists(),api.holdingsSummary()]);const ms:Record<string,Instrument[]>={};for(const g of gs)ms[g.id]=await api.watchlistMembers(g.id);if(closed)return;groups.value=gs;members.value=ms;summary.value=hs;const ids=Array.from(new Set([...Object.values(ms).flat().map(r=>r.id),...hs.items.map(r=>r.holding.instrumentId)]));for(const id of ids.filter(id=>(prepared.get(id)??0)<=Date.now()).sort((a,b)=>(prepared.get(a)??0)-(prepared.get(b)??0)).slice(0,8)){prepared.set(id,Date.now()+60000);try{const rs=await Promise.all(['bars','daily_basic'].map(endpoint=>api.ensureData({instrumentId:id,endpoint:endpoint as 'bars'|'daily_basic',years:1,force:false})));const failed=rs.find(r=>r.state==='failed');if(failed)dataFailures.set(id,connectionError(failed.message,'data'));else dataFailures.delete(id)}catch(e){dataFailures.set(id,connectionError(e,'data'))}}for(const id of dataFailures.keys())if(!ids.includes(id))dataFailures.delete(id);dataError.value=Array.from(dataFailures.values())[0]??'';for(let i=0;i<ids.length;i+=50){const qs=await api.latestQuotes(ids.slice(i,i+50));if(closed)return;for(const q of qs){quotes.value[q.instrumentId]=q;if(!q.snapshotId)changes.value[q.instrumentId]=null;if(q.snapshotId&&versions.get(q.instrumentId)!==q.snapshotId){changes.value[q.instrumentId]=null;try{const first=await api.readBars(q.snapshotId,'forward',0);const tail=first.total>first.items.length?await api.readBars(q.snapshotId,'forward',Math.max(0,first.total-2)):first;const rows=tail.items.slice(-2);if(rows.length===2&&rows[0].close>0)changes.value[q.instrumentId]=(rows[1].close/rows[0].close-1)*100;versions.set(q.instrumentId,q.snapshotId)}catch{/* Missing adjustment data stays unknown. */}}}}}catch(e){dataError.value=connectionError(e,'data')}finally{loading.value=false}}
async function action(fn:()=>Promise<unknown>){if(busy.value)return;busy.value=true;error.value='';try{await fn();await refresh();emit('changed')}catch(e){error.value=connectionError(e,'data')}finally{busy.value=false}}
watch(query,()=>{const n=++searchVersion;clearTimeout(searchTimer);searchTimer=setTimeout(async()=>{if(!query.value.trim()){matches.value=[];return}try{const result=await api?.searchInstruments(query.value,0);if(n===searchVersion&&!closed)matches.value=result?.items??[]}catch(e){error.value=connectionError(e,'data')}},180)});
function open(id:string){selected.value=id;emit('open',id)}
function context(e:MouseEvent,id:string,group=''){e.preventDefault();menu.value={id,group,x:Math.min(e.clientX,window.innerWidth-195),y:Math.max(0,Math.min(e.clientY,window.innerHeight-240))}}
async function add(i:Instrument){if(tab.value==='hold'){setHolding({instrumentId:i.id,name:i.name,quantity:0,costPrice:null,asOf:new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai'}).format(new Date()),revision:0} as Holding);return}await action(async()=>{let id=targetGroup.value||(groups.value.length===1?groups.value[0].id:undefined)||groups.value.find(g=>g.name==='默认自选')?.id;if(!id)id=(await api!.createWatchlist('默认自选')).id;await api!.addWatchlistMember(id,i.id)});}
function setHolding(h:Holding){const current=summary.value?.items.find(r=>r.holding.instrumentId===h.instrumentId)?.holding??h;edit.value={...current,costPrice:current.costPrice??''};adding.value=false;menu.value=null}
async function saveHolding(){if(!edit.value)return;const h=edit.value;await action(async()=>{await api!.saveHolding({instrumentId:h.instrumentId,quantity:h.quantity,costPrice:h.costPrice.trim()||null,asOf:h.asOf,revision:h.revision});edit.value=null})}
async function clearHolding(){const h=summary.value?.items.find(r=>r.holding.instrumentId===menu.value?.id)?.holding;if(!h)return;menu.value=null;await action(()=>api!.saveHolding({quantity:0,instrumentId:h.instrumentId,costPrice:h.costPrice,asOf:h.asOf,revision:h.revision}))}
async function remove(){const m=menu.value;if(!m)return;menu.value=null;await action(async()=>{for(const g of groups.value.filter(g=>(!m.group||g.id===m.group)&&(members.value[g.id]??[]).some(i=>i.id===m.id)))await api!.removeWatchlistMember(g.id,m.id)})}
async function move(id:string){const m=menu.value;if(!m)return;menu.value=null;await action(async()=>{await api!.addWatchlistMember(id,m.id);if(m.group&&m.group!==id)await api!.removeWatchlistMember(m.group,m.id)})}
function persist(){try{localStorage.setItem('stock:stocks-panel:'+props.project,JSON.stringify({tab:tab.value,collapsed:collapsed.value}))}catch{}}
watch([tab,collapsed],persist,{deep:true});
const unsubscribe=api?.onDataChanged(()=>void refresh());
onMounted(()=>{try{const s=JSON.parse(localStorage.getItem('stock:stocks-panel:'+props.project)||'{}');if(s.tab==='hold')tab.value='hold';if(Array.isArray(s.collapsed))collapsed.value=s.collapsed}catch{}void refresh();timer=setInterval(()=>{if(!document.hidden)void refresh()},5000)});onBeforeUnmount(()=>{closed=true;unsubscribe?.();clearInterval(timer);clearTimeout(searchTimer)});
</script>
<template><section class="stocks-browser"><div class="stocks-toolbar"><div role="tablist" aria-label="我的股票"><button role="tab" :aria-selected="tab==='watch'" @click="tab='watch';menu=null">自选</button><button role="tab" :aria-selected="tab==='hold'" @click="tab='hold';menu=null">持仓</button></div><UiButton icon="search" icon-only @click="showSearch=!showSearch">筛选股票</UiButton><UiButton icon="plus" icon-only @click="adding=!adding;edit=null">{{tab==='watch'?'添加自选':'添加持仓'}}</UiButton><UiButton v-if="tab==='watch'" icon="settings" icon-only @click="newGroup=!newGroup">管理分组</UiButton></div>
<input v-if="showSearch" class="stocks-search" v-model="filter" placeholder="名称或代码" aria-label="筛选我的股票"/>
<p v-if="error||dataError" role="alert" class="stocks-note">{{error||dataError}}</p>
<form v-if="newGroup&&tab==='watch'" class="stocks-editor" @submit.prevent="action(async()=>{await api!.createWatchlist(groupName);groupName='';newGroup=false})"><input v-model="groupName" placeholder="分组名称" required aria-label="新分组名称"/><UiButton icon="check" :disabled="busy">新建分组</UiButton></form>
<div v-if="adding" class="stocks-editor"><input v-model="query" placeholder="搜索股票名称或代码" aria-label="添加股票搜索"/><select v-if="tab==='watch'&&groups.length>1" v-model="targetGroup" aria-label="添加到分组"><option value="">默认自选</option><option v-for="g in groups" :value="g.id">{{g.name}}</option></select><button v-for="i in matches" :key="i.id" :disabled="busy" @click="add(i)">{{i.name}} <small>{{i.id}}</small></button></div>
<form v-if="edit" class="stocks-editor" @submit.prevent="saveHolding"><strong>{{edit.name}}</strong><label>股数<input type="number" v-model.number="edit.quantity" min="0" step="1" required/></label><label>成本价<input v-model="edit.costPrice" inputmode="decimal" placeholder="未知可留空"/></label><label>持仓日期<input type="date" v-model="edit.asOf" required/></label><div><UiButton icon="check" :disabled="busy">保存</UiButton><UiButton type="button" icon="close" @click="edit=null">取消</UiButton></div></form>
<div v-if="tab==='hold'&&summary" class="hold-total"><div><small>持仓市值</small><strong>{{fmt(summary.marketValue)}}</strong></div><div><small>浮动盈亏</small><strong :class="tone(summary.floatingProfit)">{{fmt(summary.floatingProfit)}}</strong></div></div>
<div class="stocks-scroll"><template v-if="tab==='watch'"><template v-for="g in (groups.length>1?visibleGroups:[{id:'',name:'',rows:flat}])" :key="g.id"><button v-if="g.name" class="stock-group" @click="collapsed=collapsed.includes(g.id)?collapsed.filter(id=>id!==g.id):[...collapsed,g.id]">{{collapsed.includes(g.id)?'›':'⌄'}} {{g.name}} <small>{{g.rows.length}}</small></button><template v-if="!collapsed.includes(g.id)"><button v-for="i in g.rows" :key="i.id" class="stock-row" :class="{selected:selected===i.id}" :title="'收盘数据 · '+(quotes[i.id]?.date??'暂无行情')+(quotes[i.id]?.collectedAt?' · 采集于 '+new Date(quotes[i.id].collectedAt!).toLocaleString():'')" @click="open(i.id)" @contextmenu="context($event,i.id,g.id)"><span>{{i.name}}<small>{{i.id}}</small></span><span class="stock-numbers">{{fmt(quotes[i.id]?.close)}}<small :class="tone(changes[i.id])">{{changes[i.id]==null?'—':fmt(changes[i.id])+'%'}}</small></span></button></template></template><p v-if="!flat.length" class="stocks-note">{{filter?'没有匹配股票':'还没有自选股票'}}</p></template>
<template v-else><button v-for="r in activeHoldings.filter(r=>match(r.holding))" :key="r.holding.instrumentId" class="stock-row" :class="{selected:selected===r.holding.instrumentId}" :title="'收盘数据 · '+(r.priceDate??'暂无行情')+(quotes[r.holding.instrumentId]?.collectedAt?' · 采集于 '+new Date(quotes[r.holding.instrumentId].collectedAt!).toLocaleString():'')" @click="open(r.holding.instrumentId)" @contextmenu="context($event,r.holding.instrumentId)"><span>{{r.holding.name}}<small>{{r.holding.instrumentId}}</small></span><span class="stock-numbers">{{fmt(r.price)}}<small :class="tone(r.floatingProfit)">{{fmt(r.floatingProfit)}}</small></span></button><p v-if="!activeHoldings.length" class="stocks-note">尚未记录持仓</p></template></div><small class="stocks-footnote">最新已存收盘数据</small>
<Teleport to="body"><template v-if="menu"><div class="stocks-dismiss" @click="menu=null"/><div class="stocks-menu" :style="{left:menu.x+'px',top:menu.y+'px'}"><button @click="open(menu.id);menu=null">查看股票</button><template v-if="tab==='hold'"><button @click="setHolding(summary!.items.find(r=>r.holding.instrumentId===menu!.id)!.holding)">修改持仓</button><button :disabled="busy" @click="clearHolding">清空持仓</button></template><template v-else><button :disabled="busy" @click="remove">移除自选</button><small v-if="groups.length>1">移入分组</small><button v-for="g in groups.filter(g=>g.id!==menu!.group)" :disabled="busy" @click="move(g.id)">{{g.name}}</button></template></div></template></Teleport>
</section></template>
<style scoped>
.stocks-browser{display:flex;flex-direction:column;flex:1;min-height:0;overflow:hidden}.stocks-toolbar{display:flex;align-items:center;height:34px;flex:none;border-bottom:1px solid var(--line);padding:0 4px}.stocks-toolbar>div{display:flex;flex:1}.stocks-toolbar button{padding:4px 8px;min-height:28px}.stocks-toolbar [role=tab]{position:relative;color:var(--muted);height:34px}.stocks-toolbar [aria-selected=true]{color:var(--text)}.stocks-toolbar [aria-selected=true]::after{content:'';position:absolute;bottom:0;left:8px;right:8px;height:1px;background:var(--accent)}.stocks-toolbar .ui-icon-only{width:28px;min-width:28px;height:28px;padding:5px}.stocks-search{margin:8px;width:calc(100% - 16px);min-height:28px;padding:4px 8px}.stocks-scroll{overflow:auto;min-height:0;flex:1}.stock-row{width:100%;display:flex;align-items:center;justify-content:space-between;gap:8px;text-align:left;padding:7px 12px;border-radius:0;min-height:44px;font-size:13px}.stock-row>span:first-child{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.stock-row small{display:block;font-size:11px;color:var(--muted);margin-top:3px}.stock-numbers{text-align:right;flex:none;font-variant-numeric:tabular-nums}.stock-row.selected{background:var(--accent-soft)!important}.stock-row:hover{background:var(--raised)!important}.stock-group{width:100%;display:flex;gap:6px;text-align:left;padding:5px 10px;font-size:12px}.stock-group small{margin-left:auto;color:var(--muted)}.stocks-note{font-size:12px;color:var(--muted);padding:10px}.hold-total{padding:12px;display:grid;gap:10px;border-bottom:1px solid var(--line)}.hold-total>div{display:flex;justify-content:space-between;gap:6px}.hold-total small{color:var(--muted)}.hold-total strong{font-size:13px;font-weight:500;font-variant-numeric:tabular-nums}.stocks-editor{display:grid;gap:8px;padding:10px;max-height:50vh;overflow:auto}.stocks-editor input,.stocks-editor select{width:100%;min-height:28px;padding:4px 6px}.stocks-editor label{display:grid;gap:4px;font-size:12px}.stocks-editor button{text-align:left}.stocks-editor>div{display:flex;gap:4px}.stocks-editor small{color:var(--muted)}.stocks-footnote{padding:6px 12px;color:var(--muted);font-size:11px}.rise{color:#ee8585!important}.fall{color:#64bca0!important}.stocks-dismiss{position:fixed;inset:0;z-index:999}.stocks-menu{position:fixed;z-index:1000;width:190px;max-height:240px;overflow:auto;padding:4px;background:#151e28;border:1px solid var(--line);border-radius:6px;box-shadow:0 6px 24px #0006}.stocks-menu button{display:block;width:100%;text-align:left;background:transparent;border:0;padding:5px 10px;font-size:13px}.stocks-menu button:hover{background:#233142}.stocks-menu>small{display:block;color:var(--muted);padding:6px 10px}
</style>
