<script setup lang="ts">
import UiButton from './UiButton.vue';
import SettingsMore from './SettingsMore.vue';
import {ref,onMounted} from 'vue';
import type {DesktopBridge} from '../../../../packages/contracts/desktop';
const data=ref<Awaited<ReturnType<DesktopBridge['nativeMcpRead']>>|null>(null),busy=ref(false),error=ref(''),notice=ref('');
const name=ref(''),kind=ref('http'),url=ref(''),command=ref(''),args=ref('[]');
async function action(fn:()=>Promise<void>){if(!window.stock||busy.value)return;busy.value=true;error.value='';notice.value='';try{await fn()}catch(e){error.value=e instanceof Error?e.message:'MCP 配置未完成。'}finally{busy.value=false}}
async function openConfig(){await window.stock?.openManagedLocation('config')}
async function read(){data.value=await window.stock!.nativeMcpRead()}
async function write(change:Record<string,unknown>){if(!data.value?.version)return;data.value=await window.stock!.nativeMcpWrite({...change,version:data.value.version,project:data.value.project});notice.value=data.value.servers.some(s=>s.name===change.name&&s.effectiveEnabled!==s.enabled)?'已保存用户配置，但当前项目的有效启停状态不同，请检查项目配置。':'已保存，下次连接生效。'}
async function add(){let definition;if(kind.value==='http')definition={url:url.value.trim()};else{let parsed;try{parsed=JSON.parse(args.value)}catch{throw Error('参数需填写 JSON 字符串数组，例如 ["--port", "3000"]。')}definition={command:command.value.trim(),args:parsed}}await write({name:name.value.trim(),definition});name.value='';url.value='';command.value='';args.value='[]'}
onMounted(()=>action(read));
</script>
<template><section class="settings-section native-mcp-settings"><div class="section-description"><h2>自定义 MCP</h2><SettingsMore><UiButton icon="folder" :disabled="busy" @click="action(openConfig)">管理配置文件</UiButton></SettingsMore></div><div class="settings-form"><p v-if="busy&&!data" role="status">正在加载配置…</p><template v-if="data"><p v-if="!data.servers.length" class="setting-muted">尚未添加服务</p><div v-for="server in data.servers" :key="server.name" class="setting-row"><div><strong>{{server.name}}</strong><small class="setting-muted">{{server.type}}</small><small v-if="server.effectiveEnabled!==null&&server.effectiveEnabled!==server.enabled" class="setting-muted">项目设置覆盖了此开关</small></div><input class="setting-switch" type="checkbox" role="switch" :aria-label="'启用 '+server.name" :checked="server.enabled" :disabled="busy||!data.version" @change="action(()=>write({name:server.name,enabled:!server.enabled}))"></div><details><summary>添加工具服务</summary><form @submit.prevent="action(add)"><label for="mcp-name">服务名</label><input id="mcp-name" v-model="name" maxlength="64" required><label for="mcp-kind">连接方式</label><select id="mcp-kind" v-model="kind"><option value="http">HTTP MCP</option><option value="stdio">本地命令（stdio）</option></select><template v-if="kind==='http'"><label for="mcp-url">服务 URL</label><input id="mcp-url" v-model="url" placeholder="https://example.com/mcp" required></template><template v-else><label for="mcp-command">可执行文件或命令</label><input id="mcp-command" v-model="command" required><label for="mcp-args">参数（JSON 数组）</label><textarea id="mcp-args" v-model="args" rows="3"/></template><UiButton icon="plus" type="submit" :disabled="busy||!data.version">添加 MCP</UiButton></form></details></template><p v-if="notice" role="status">{{notice}}</p><p v-if="error" role="alert">{{error}} <UiButton icon="refresh" :disabled="busy" @click="action(read)">重试加载</UiButton></p></div></section></template>
<style scoped>form{display:flex;flex-direction:column;gap:10px;margin-top:12px}input,textarea,select{max-width:100%;box-sizing:border-box}textarea{resize:vertical}details>summary{cursor:pointer}</style>
