<script setup lang="ts">
import {connectionError} from './connection-error';
import {renderCopilotMarkdown} from './copilot-markdown.mjs';
import UiButton from './UiButton.vue';
import ProjectDocumentPreview from './ProjectDocumentPreview.vue';
import {computed,onMounted,onBeforeUnmount,ref,watch} from 'vue';
const emit=defineEmits<{guard:[blocked:boolean];open:[path:string]}>();
const persisted=ref(true);
const props=defineProps<{path:string;project:string}>();
const imageUrl=ref(''),imageZoom=ref(1);
const metadata=ref<Awaited<ReturnType<NonNullable<Window['stock']>['projectDescribe']>>|null>(null);
const isDocument=computed(()=>/\.(pdf|xlsx|csv|tsv)$/i.test(props.path));
const isImage=computed(()=>/\.(png|jpg|jpeg|gif|webp)$/i.test(props.path));
const isMarkdown=computed(()=>/\.(md|markdown)$/i.test(props.path));
const text=ref(''),base=ref(''),revision=ref(''),modified=ref(''),error=ref(''),notice=ref(''),busy=ref(false),editing=ref(false),loaded=ref(false),disk=ref<{text:string;revision:string}|null>(null);
const dirty=computed(()=>text.value!==base.value),draftKey=`stock.file-draft:${props.project}:${props.path}`;
function persist(){if(!loaded.value)return;try{if(dirty.value)window.localStorage.setItem(draftKey,JSON.stringify({text:text.value,base:base.value,revision:revision.value}));else window.localStorage.removeItem(draftKey);persisted.value=true;emit('guard',false)}catch{persisted.value=false;emit('guard',true);error.value='本地草稿无法保存。请先保存文件再关闭页面。'}}
watch(text,persist,{flush:'sync'});
async function read(){if(!window.stock||busy.value)return;busy.value=true;error.value='';try{metadata.value=await window.stock.projectDescribe(props.path);if(isDocument.value)return;if(isImage.value){imageUrl.value=await window.stock.projectImage(props.path);return}const result=await window.stock.projectRead(props.path);modified.value=result.modifiedAt;if(dirty.value){disk.value={text:result.text,revision:result.revision};notice.value='草稿保留。可展开磁盘版本对照合并。'}else{loaded.value=false;text.value=result.text;base.value=result.text;revision.value=result.revision;loaded.value=true;disk.value=null}}catch(e){error.value=connectionError(e,'data')}finally{busy.value=false}}
async function save(){if(!window.stock||busy.value||!dirty.value||disk.value)return;busy.value=true;error.value='';try{const result=await window.stock.projectWrite(props.path,text.value,revision.value);base.value=result.text;revision.value=result.revision;modified.value=result.modifiedAt;disk.value=null;persist();notice.value='已保存。恢复副本：'+result.backup}catch(e){error.value=connectionError(e,'data')}finally{busy.value=false}}
async function openInSystem(){try{await window.stock!.projectOpenExternal(props.path)}catch{try{await window.stock!.projectReveal(props.path)}catch{error.value='文件无法打开，请检查是否已移动或删除。'}}}
function markdownClick(event:MouseEvent){const link=(event.target as HTMLElement).closest('a');if(link?.dataset.projectFile){event.preventDefault();emit('open',link.dataset.projectFile)}}
function merged(){if(!disk.value)return;revision.value=disk.value.revision;base.value=disk.value.text;disk.value=null;persist();notice.value='已采用磁盘新版作为基础，可以保存合并后的草稿。'}
function beforeUnload(event:BeforeUnloadEvent){if(dirty.value&&!persisted.value){event.preventDefault();event.returnValue='文件草稿尚未保存'}}
onBeforeUnmount(()=>{window.removeEventListener('beforeunload',beforeUnload);emit('guard',false)});
onMounted(async()=>{window.addEventListener('beforeunload',beforeUnload);await read();try{const draft=JSON.parse(window.localStorage.getItem(draftKey)??'null');if(draft&&typeof draft.text==='string'&&typeof draft.base==='string'&&typeof draft.revision==='string'){if(draft.revision!==revision.value)disk.value={text:base.value,revision:revision.value};loaded.value=false;text.value=draft.text;base.value=draft.base;revision.value=draft.revision;loaded.value=true;editing.value=true;notice.value='已恢复本地未保存草稿。'}}catch{error.value='无法恢复本地草稿。'}});
</script>
<template><section class="project-file"><header><span>{{path}} {{dirty?'· 未保存':''}}</span><div><UiButton v-if="!isImage&&!isDocument" icon="edit" icon-only :disabled="busy||!loaded" @click="editing=!editing">{{editing?'阅读':'编辑'}}</UiButton><select v-if="isImage" v-model="imageZoom" aria-label="图片缩放"><option :value="0.5">50%</option><option :value="1">100%</option><option :value="1.5">150%</option><option :value="2">200%</option></select><UiButton v-if="!isDocument" icon="refresh" icon-only :disabled="busy" @click="read">刷新文件</UiButton><UiButton v-if="!isDocument" icon="folder" icon-only @click="openInSystem">系统打开</UiButton><UiButton v-if="editing" icon="save" class="primary" :disabled="busy||!dirty||!!disk" @click="save">保存</UiButton></div></header><p v-if="metadata?.source" class="source-meta">{{metadata.source.title}} · {{new Date(metadata.source.collectedAt).toLocaleString()}} <a :href="metadata.source.url" target="_blank" rel="noopener noreferrer">原始来源</a></p><p v-if="error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p><ProjectDocumentPreview v-if="isDocument" :path="path"/><textarea v-else-if="editing" v-model="text" :disabled="busy" aria-label="编辑项目文件" spellcheck="false" @keydown.ctrl.s.prevent="save"/><div v-else-if="isImage&&imageUrl" class="project-image-scroll"><img :src="imageUrl" :alt="path" class="project-image" :style="{width:imageZoom*100+'%'}"/></div><div v-else-if="isMarkdown" class="project-markdown" v-html="renderCopilotMarkdown(text,project,path)" @click="markdownClick"/><pre v-else>{{text}}</pre><details v-if="disk" open><summary>磁盘新版 · 与上方草稿对照</summary><pre>{{disk.text}}</pre><UiButton icon="save" :disabled="busy" @click="merged">已合并，采用此版本作为保存基础</UiButton></details></section></template>
<style scoped>.project-image-scroll{overflow:auto;max-height:70vh;margin:20px 0}.project-image{display:block;max-width:none;max-height:none;object-fit:contain}.project-markdown{max-width:900px;line-height:1.8;margin-top:20px}.project-markdown :deep(p){margin:12px 0}.project-markdown :deep(table){border-collapse:collapse}.project-markdown :deep(td),.project-markdown :deep(th){padding:6px 12px;border:1px solid var(--line)}.project-file{padding:18px 24px;min-width:0}.project-file header{display:flex;gap:12px;align-items:center;justify-content:space-between;flex-wrap:wrap}.project-file header>div{display:flex;gap:6px;flex-wrap:wrap;max-width:100%}.project-file header span{overflow-wrap:anywhere;min-width:0}.project-file small{display:block;margin:10px 0;color:var(--muted)}.project-file pre,.project-file textarea{white-space:pre-wrap;overflow-wrap:anywhere;font:1.0rem/1.8 'Cascadia Code',Consolas,monospace;color:var(--text)}.project-file textarea{width:100%;min-height:50vh;resize:vertical}.project-file p[role=alert]{color:var(--danger)}.project-file p[role=status]{font-size:0.923077rem;overflow-wrap:anywhere;color:var(--muted)}.project-file details{margin-top:20px;border-top:1px solid var(--line);padding-top:12px}</style>
