<script setup lang="ts">
import UiButton from './UiButton.vue';
import {computed,nextTick,onMounted,onBeforeUnmount,ref,watch} from 'vue';
const props=defineProps<{project:string}>();
const emit=defineEmits<{open:[path:string];select:[]}>();
type Entry={name:string;path:string;directory:boolean;link:boolean};
const cache=ref<Record<string,Entry[]>>({}),expanded=ref<string[]>([]),selected=ref(''),query=ref(''),searching=ref(false),results=ref<Entry[]>([]),error=ref(''),limited=ref(false),busy=ref(false),scroll=ref<HTMLElement>(),searchInput=ref<HTMLInputElement>();
const menu=ref<{entry:Entry|null;x:number;y:number}|null>(null),editor=ref<{action:'file'|'folder'|'rename';path:string;name:string}|null>(null);
const key='stock:tree:'+props.project;let timer:ReturnType<typeof setInterval>,debounce:ReturnType<typeof setTimeout>,generation=0,disposed=false;
const projectName=computed(()=>props.project.split(/[\\/]/).filter(Boolean).pop()||'项目');
const rows=computed(()=>{if(query.value.trim())return results.value.map(e=>({...e,depth:0}));const list:(Entry&{depth:number})[]=[];function walk(dir:string,depth:number){for(const e of cache.value[dir]??[]){list.push({...e,depth});if(e.directory&&expanded.value.includes(e.path))walk(e.path,depth+1)}}walk('',0);return list});
function moveTree(event:KeyboardEvent){if(!['ArrowDown','ArrowUp','Home','End'].includes(event.key))return;event.preventDefault();const all=Array.from(scroll.value?.querySelectorAll<HTMLButtonElement>('.tree-row')??[]),i=all.indexOf(event.target as HTMLButtonElement);all[event.key==='Home'?0:event.key==='End'?all.length-1:Math.max(0,Math.min(all.length-1,i+(event.key==='ArrowDown'?1:-1)))]?.focus()}
function remember(){try{localStorage.setItem(key,JSON.stringify({expanded:expanded.value,selected:selected.value,scroll:scroll.value?.scrollTop??0}))}catch{}}
async function refresh(){if(!window.stock||busy.value)return;busy.value=true;try{for(const dir of ['',...expanded.value]){try{const page=await window.stock.projectList(dir);if(disposed)return;cache.value[dir]=page.entries}catch{if(!dir)throw Error('无法读取项目文件。')}}}catch(e){error.value=String(e)}finally{busy.value=false}}
async function activate(e:Entry){selected.value=e.path;if(e.directory){if(expanded.value.includes(e.path))expanded.value=expanded.value.filter(p=>p!==e.path);else{expanded.value.push(e.path);await refresh()}}else emit('open',e.path);remember()}
async function find(){const n=++generation,q=query.value.trim();if(!q){results.value=[];limited.value=false;return}try{const page=await window.stock?.projectSearch(q);if(n===generation&&page&&!disposed){results.value=page.entries;limited.value=page.truncated}}catch(e){error.value=String(e)}}
watch(query,()=>{generation++;clearTimeout(debounce);debounce=setTimeout(find,180)});
async function showSearch(){searching.value=!searching.value;if(!searching.value)query.value='';await nextTick();searchInput.value?.focus()}
function context(event:MouseEvent,e:Entry|null){event.preventDefault();menu.value={entry:e,x:Math.min(event.clientX,window.innerWidth-190),y:Math.max(0,Math.min(event.clientY,window.innerHeight-260))}}
function edit(action:'file'|'folder'|'rename'){const e=menu.value?.entry;editor.value={action,path:action==='rename'?e!.path:e?.directory?e.path:e?.path.split('/').slice(0,-1).join('/')||'',name:action==='rename'?e!.name:''};menu.value=null}
async function save(){if(!editor.value||!window.stock)return;try{const old=editor.value;const result=await window.stock.projectManage({...old});if(old.action==='rename'){expanded.value=expanded.value.map(p=>p===old.path||p.startsWith(old.path+'/')?result.path+p.slice(old.path.length):p)}const parent=result.path.split('/').slice(0,-1).join('/');if(parent&&!expanded.value.includes(parent))expanded.value.push(parent);selected.value=result.path;editor.value=null;await refresh();if(query.value)await find();remember()}catch(e){error.value=String(e)}}
async function reveal(){try{await window.stock?.projectReveal(menu.value?.entry?.path||'')}catch(e){error.value=String(e)}menu.value=null}
async function copy(){try{await navigator.clipboard.writeText(menu.value?.entry?.path||'')}catch{error.value='复制失败。'}menu.value=null}
function dismiss(event:KeyboardEvent){if(event.key==='Escape'){menu.value=null;editor.value=null}}
onMounted(async()=>{let top=0;try{const saved=JSON.parse(localStorage.getItem(key)||'{}');expanded.value=Array.isArray(saved.expanded)?saved.expanded.filter((p:unknown)=>typeof p==='string'):[];selected.value=saved.selected||'';top=saved.scroll||0}catch{}await refresh();await nextTick();if(scroll.value)scroll.value.scrollTop=top;timer=setInterval(()=>{if(!document.hidden){void refresh();if(query.value)void find()}},3000);window.addEventListener('keydown',dismiss)});
onBeforeUnmount(()=>{disposed=true;remember();clearInterval(timer);clearTimeout(debounce);window.removeEventListener('keydown',dismiss)});
</script>
<template><section class="project-browser">
<header class="project-tree-header"><strong :title="projectName">{{projectName}}</strong><UiButton icon="search" icon-only @click="showSearch">搜索文件</UiButton><UiButton icon="settings" icon-only @click="context($event,null)">项目菜单</UiButton></header>
<div v-if="searching" class="tree-search"><input ref="searchInput" v-model="query" aria-label="搜索文件名" placeholder="搜索文件…" @keydown.esc="searching=false;query=''"/></div>
<p v-if="error" role="alert" class="tree-notice">{{error}}</p>
<form v-if="editor" class="tree-editor" @submit.prevent="save"><label>{{editor.action==='rename'?'重命名':editor.action==='folder'?'新建目录':'新建文件'}}<input v-model="editor.name" required autofocus aria-label="文件名称"/></label><div><UiButton icon="check">确定</UiButton><UiButton icon="close" type="button" @click="editor=null">取消</UiButton></div></form>
<div ref="scroll" class="tree-scroll" role="tree" aria-label="项目文件" @keydown="moveTree" @scroll="remember" @contextmenu.self="context($event,null)">
<button v-for="e in rows" :key="e.path" role="treeitem" :aria-level="e.depth+1" :aria-expanded="e.directory?expanded.includes(e.path):undefined" :aria-selected="selected===e.path" class="tree-row" :style="{paddingLeft:(8+e.depth*14)+'px'}" :title="e.path" @click="activate(e)" @contextmenu="context($event,e)" @keydown.right.prevent="e.directory&&!expanded.includes(e.path)&&activate(e)" @keydown.left.prevent="e.directory&&expanded.includes(e.path)&&activate(e)"><svg class="tree-arrow" viewBox="0 0 24 24" :class="{expanded:expanded.includes(e.path)}"><path v-if="e.directory" d="m9 6 6 6-6 6"/></svg><svg class="tree-file-icon" viewBox="0 0 24 24"><path :d="e.directory?'M3 6h7l2 3h9v11H3Z':/\.(png|jpg|jpeg|gif|webp)$/i.test(e.name)?'M3 3h18v18H3ZM3 17l6-6 4 4 3-3 5 5M15 7h1':/\.(js|ts|py|json|toml|yaml|yml)$/i.test(e.name)?'m8 7-5 5 5 5m8-10 5 5-5 5M14 4l-4 16':'M5 3h9l5 5v13H5ZM14 3v6h5M8 13h8M8 17h6'"/></svg><span class="tree-name">{{e.name}}<small v-if="query">{{e.path}}</small></span></button>
<p v-if="!rows.length&&!busy" class="tree-notice">{{query?'没有匹配文件':'暂无文件'}}</p><p v-if="limited&&query" class="tree-notice">结果较多，请缩小搜索范围。</p></div>
<Teleport to="body"><template v-if="menu"><div class="tree-menu-dismiss" @click="menu=null" @contextmenu.prevent="menu=null"/><div class="tree-menu" :style="{left:menu.x+'px',top:menu.y+'px'}"><button v-if="menu.entry" @click="activate(menu.entry);menu=null">打开</button><button @click="edit('file')">新建文件</button><button @click="edit('folder')">新建目录</button><button v-if="menu.entry" @click="edit('rename')">重命名</button><button v-if="menu.entry" @click="copy">复制相对路径</button><button @click="reveal">在系统中显示</button><button v-if="!menu.entry" @click="emit('select');menu=null">切换项目…</button></div></template></Teleport>
</section></template>
<style scoped>
.project-browser{display:flex;flex-direction:column;min-height:0;flex:1;overflow:hidden}.project-tree-header{height:34px;min-height:34px;display:flex;align-items:center;padding:2px 8px;gap:2px;border-bottom:1px solid var(--line)}.project-tree-header strong{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:13px;font-weight:500}.project-tree-header .ui-action{width:28px;min-width:28px;height:28px;min-height:28px;padding:5px}.tree-search,.tree-editor{padding:8px}.tree-search input,.tree-editor input{width:100%;min-height:28px;padding:4px 8px}.tree-editor label{display:grid;gap:6px}.tree-editor>div{display:flex;gap:6px;margin-top:6px}.tree-scroll{overflow:auto;flex:1;min-height:0;padding:4px 0}.tree-row{display:flex;align-items:center;width:100%;min-height:28px;padding:4px 8px;gap:5px;border:0;border-radius:0;text-align:left;font-size:13px}.tree-row[aria-selected=true]{background:var(--accent-soft)!important;color:var(--text)}.tree-row:hover{background:var(--raised)!important}.tree-arrow,.tree-file-icon{width:14px;height:14px;flex:none;fill:none;stroke:currentColor;stroke-width:1.5;stroke-linecap:round;stroke-linejoin:round;color:var(--muted)}.tree-arrow{width:10px}.tree-arrow.expanded{transform:rotate(90deg)}.tree-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.tree-name small{display:block;overflow:hidden;text-overflow:ellipsis;color:var(--muted);font-size:11px}.tree-notice{padding:8px 12px;color:var(--muted);font-size:12px}.tree-menu-dismiss{position:fixed;inset:0;z-index:999}.tree-menu{position:fixed;z-index:1000;width:180px;padding:4px;background:#151e28;border:1px solid var(--line);border-radius:6px;box-shadow:0 6px 24px #0006}.tree-menu button{display:block;width:100%;text-align:left;background:transparent;border:0;min-height:28px;padding:5px 10px;font-size:13px}.tree-menu button:hover{background:#233142}
</style>
