<script setup lang="ts">
import {ref,onMounted,onBeforeUnmount} from 'vue';
import {connectionError} from './connection-error';
import UiButton from './UiButton.vue';
const activeTab=ref<'tasks'|'runs'>('tasks');
function switchTab(event:KeyboardEvent){if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();activeTab.value=event.key==='Home'?'tasks':event.key==='End'?'runs':activeTab.value==='tasks'?'runs':'tasks';const list=(event.currentTarget as HTMLElement).parentElement;requestAnimationFrame(()=>list?.querySelector<HTMLButtonElement>('[aria-selected="true"]')?.focus())}
const emit=defineEmits<{open:[]}>();
const api=window.stock,state=ref<any>({tasks:[],runs:[]}),edit=ref<any>(null),busy=ref(false),error=ref('');let off:(()=>void)|undefined;
function retryable(r:any){return ['failed','interrupted','skipped'].includes(r.status)&&state.value.tasks.some((t:any)=>t.id===r.taskId)}
const labels:Record<string,string>={starting:'启动中',running:'运行中',waiting:'等待批准或回答',succeeded:'完成',failed:'失败',skipped:'已跳过',interrupted:'已停止'};
async function refresh(){if(api)state.value=await api.schedulerList()}
async function action(fn:()=>Promise<any>){if(busy.value)return;busy.value=true;error.value='';try{await fn();await refresh()}catch(e){error.value=connectionError(e,'model')}finally{busy.value=false}}
function draft(t?:any){edit.value=t?{id:t.id,name:t.name,prompt:t.prompt,frequency:t.frequency,cron:t.cron??'*/30 * * * * *',intervalSeconds:t.intervalSeconds??30,time:t.time,timezone:t.timezone,enabled:t.enabled,permissionMode:t.permissionMode,notifyEnabled:t.notifyEnabled??false}:{name:'',prompt:'',frequency:'weekdays',cron:'*/30 * * * * *',intervalSeconds:30,time:'15:30',timezone:'Asia/Shanghai',enabled:true,permissionMode:'ask',notifyEnabled:false}}
async function toggle(t:any){const {project,lastSlot,nextDue,threadId,...value}=t;await api?.schedulerSave({...value,enabled:!t.enabled})}
onMounted(()=>{void action(refresh);off=api?.onSchedulerChanged(()=>void refresh().catch(e=>error.value=connectionError(e,'model')))});onBeforeUnmount(()=>off?.());
</script>
<template><div class="scheduler-panel"><div class="scheduler-tools"><div class="scheduler-tabs" role="tablist" aria-label="Scheduler"><button id="scheduler-tasks-tab" role="tab" :aria-selected="activeTab==='tasks'" :tabindex="activeTab==='tasks'?0:-1" aria-controls="scheduler-tasks-panel" @keydown="switchTab" @click="activeTab='tasks'">任务</button><button id="scheduler-runs-tab" role="tab" :aria-selected="activeTab==='runs'" :tabindex="activeTab==='runs'?0:-1" aria-controls="scheduler-runs-panel" @keydown="switchTab" @click="activeTab='runs'">运行记录</button></div><UiButton v-if="activeTab==='tasks'" icon="plus" icon-only @click="draft()">新建定时任务</UiButton></div>
<p v-if="error||state.error" role="alert">{{error||state.error}}</p>
<section v-show="activeTab==='tasks'" id="scheduler-tasks-panel" role="tabpanel" aria-labelledby="scheduler-tasks-tab"><form v-if="edit" @submit.prevent="action(async()=>{await api?.schedulerSave({...edit});edit=null})" class="schedule-form">
<label>名称<input v-model="edit.name" required maxlength="80" aria-label="任务名称"></label><label>任务内容<textarea v-model="edit.prompt" required maxlength="10000" rows="4" aria-label="定时任务内容"/></label>
<label>频率<select v-model="edit.frequency"><option value="weekdays">工作日</option><option value="daily">每天</option><option value="hourly">每小时</option><option value="interval">固定间隔</option><option value="cron">Cron 表达式</option></select></label><label v-if="edit.frequency==='cron'">Cron<input v-model="edit.cron" required maxlength="200" aria-label="Cron 表达式" placeholder="*/30 * * * * *"><small>秒 分 时 日 月 周；也支持不含秒的五字段。</small></label><label v-else-if="edit.frequency==='interval'">间隔（秒）<input type="number" v-model.number="edit.intervalSeconds" min="30" max="86400" step="1" required aria-label="执行间隔秒数"></label><label v-else>{{edit.frequency==='hourly'?'每小时的分钟（忽略小时）':'时间'}}<input type="time" v-model="edit.time" required></label><label>时区<input v-model="edit.timezone" required placeholder="Asia/Shanghai"></label>
<label>提醒<select v-model="edit.notifyEnabled"><option :value="false">关闭</option><option :value="true">重要变化</option></select></label><label>审批<select v-model="edit.permissionMode"><option value="ask">请求批准</option><option value="auto-review">帮我审批</option><option value="full-access">完全访问权限</option></select></label><small>使用运行时的模型连接。工作日不排除交易所节假日。</small><small>后台驻留时执行；退出期间不补跑。唤醒或网络恢复后最多合并尝试一个任务，其他任务等待后续计划。</small>
<div><UiButton icon="check" :disabled="busy">保存任务</UiButton><UiButton type="button" icon="close" @click="edit=null">取消</UiButton></div></form>
<p v-if="!state.tasks.length&&!edit" class="empty">还没有定时任务。</p>
<article v-for="t in state.tasks" :key="t.id" class="schedule-task"><strong>{{t.name}}</strong><small>{{t.frequency==='cron'?t.cron:t.frequency==='interval'?'每 '+t.intervalSeconds+' 秒':t.frequency==='hourly'?'每小时 '+t.time.slice(3)+' 分':(t.frequency==='weekdays'?'工作日 ':'每天 ')+t.time}} · {{t.timezone}}</small><small v-if="t.enabled&&t.nextDue">下次：{{new Date(t.nextDue).toLocaleString('zh-CN',{timeZone:t.timezone})}}</small><p>{{t.prompt}}</p><div class="task-actions"><UiButton :icon="t.enabled?'stop':'send'" icon-only :disabled="busy" @click="action(()=>toggle(t))">{{t.enabled?'暂停定时任务':'启用定时任务'}}</UiButton><small>{{t.enabled?'已启用':'已暂停'}}</small><UiButton icon="send" icon-only :disabled="busy" @click="action(async()=>{await api!.schedulerRun(t.id);activeTab='runs'})">立即运行</UiButton><UiButton icon="edit" icon-only @click="draft(t)">编辑任务</UiButton><UiButton icon="trash" icon-only :disabled="busy" @click="action(()=>api!.schedulerRemove(t.id))">删除任务</UiButton></div></article>
</section><section v-show="activeTab==='runs'" id="scheduler-runs-panel" role="tabpanel" aria-labelledby="scheduler-runs-tab" class="schedule-runs"><p v-if="!state.runs.length" class="empty">暂无运行记录。</p><article v-for="r in state.runs" :key="r.id"><strong>{{r.name}}</strong><small>{{new Date(r.startedAt).toLocaleString()}} · {{labels[r.status]||r.status}}</small><p v-if="r.message">{{r.message}}</p><p v-if="r.notification">{{r.notification.message}}<small>{{r.notification.status==='submitted'?'已提交系统提醒':r.notification.status==='unavailable'?'系统提醒不可用':'提醒处理中'}}</small></p><UiButton v-if="r.threadId||r.blockingThreadId" icon="message" :disabled="busy" @click="action(async()=>{emit('open');await api!.schedulerOpen(r.threadId||r.blockingThreadId,r.threadId?r.turnId:undefined)})">{{r.blockingThreadId?'查看等待中的会话':r.status==='waiting'?'处理待办':'打开会话'}}</UiButton><UiButton v-if="retryable(r)" icon="refresh" :disabled="busy" @click="action(()=>api!.schedulerRun(r.taskId))">重试任务</UiButton></article></section></div></template>
<style scoped>
.scheduler-panel{padding:10px 12px;overflow:auto;min-height:0;font-size:13px}.scheduler-tools,.task-actions{display:flex;align-items:center;gap:4px}.scheduler-tools>small{flex:1}small{display:block;color:var(--muted);font-size:11px;line-height:1.6}.schedule-form{display:grid;gap:10px;padding:12px 0}.schedule-form label{display:grid;gap:5px}.schedule-form input,.schedule-form textarea,.schedule-form select{width:100%;min-width:0;box-sizing:border-box}.schedule-task,.schedule-runs article{padding:12px 0;border-bottom:1px solid var(--border)}.schedule-task p{display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden;line-height:1.5;overflow-wrap:anywhere}.task-actions small{flex:1}.schedule-runs{margin-top:0}.schedule-runs p{overflow-wrap:anywhere}.empty{color:var(--muted)}
.scheduler-tools{position:sticky;top:-10px;z-index:1;background:var(--surface,#101720);margin:-10px -12px 0;padding:0 8px;border-bottom:1px solid var(--line)}.scheduler-tabs{display:flex;flex:1;gap:4px}.scheduler-tabs button{position:relative;padding:12px 10px;color:var(--muted);font:inherit;border:0;background:transparent;cursor:pointer}.scheduler-tabs button[aria-selected="true"]{color:var(--text)}.scheduler-tabs button[aria-selected="true"]::after{content:"";position:absolute;left:10px;right:10px;bottom:0;height:1px;background:var(--accent)}.scheduler-tabs button:hover{color:var(--text)}
</style>
