<script setup lang="ts">
import {ref,computed,onMounted,onBeforeUnmount} from 'vue';
import type {SectorHistory} from '../../../../packages/contracts/generated';
import {useSectors} from './use-sectors';
import {useMarket,marketNumber as fmt} from './use-market';
import UiButton from './UiButton.vue';
const props=defineProps<{id:string;colorMode:string}>();const emit=defineEmits<{open:[id:string];loaded:[id:string,name:string];changed:[]}>();
const {sectors,sectorError,sectorUpdating,refreshSectors}=useSectors();const {breadth}=useMarket();
const sector=computed(()=>sectors.value?.items.find(s=>s.id===props.id));const history=ref<SectorHistory|null>(null),error=ref(''),loading=ref(false),query=ref(''),sort=ref('pct'),page=ref(1),notice=ref(''),adding=ref('');let timer:ReturnType<typeof setTimeout>,closed=false,busy=false;
const quotes=computed(()=>new Map((breadth.value?.items??[]).map(r=>[r.instrumentId,r])));
const members=computed(()=>(sector.value?.members??[]).filter(m=>`${m.name} ${m.instrumentId}`.toLowerCase().includes(query.value.toLowerCase())).map(m=>({...m,quote:quotes.value.get(m.instrumentId)})).sort((a,b)=>sort.value==='amount'?(b.quote?.amount??-Infinity)-(a.quote?.amount??-Infinity):(b.quote?.pct??-Infinity)-(a.quote?.pct??-Infinity)));
const tone=(n:number|null|undefined)=>n==null||n===0?'':((n>0)===(props.colorMode==='red-up')?'rise':'fall');
const points=computed(()=>{const a=history.value?.items??[];if(a.length<2)return '';const min=Math.min(...a.map(r=>r.close)),max=Math.max(...a.map(r=>r.close));return a.map((r,i)=>`${i/(a.length-1)*1000},${180-(r.close-min)/(max-min||1)*160}`).join(' ')});
async function refresh(force=false){if(busy||closed)return;busy=true;try{const api=window.stock!;const cached=await api.readSectorHistory(props.id);if(closed)return;history.value=cached;const result=await api.ensureSectorHistory(props.id,force);if(closed)return;loading.value=result.state==='updating';error.value=result.message;const fresh=await api.readSectorHistory(props.id);if(!closed)history.value=fresh}catch(e){if(!closed){error.value=String(e);loading.value=false}}finally{busy=false;if(!closed){clearTimeout(timer);timer=setTimeout(()=>void refresh(),loading.value?3000:60000)}}}
async function add(id:string){if(adding.value)return;adding.value=id;notice.value='';try{const api=window.stock!,groups=await api.watchlists();let group=groups.find(g=>g.name==='默认自选')??(groups.length===1?groups[0]:null);if(!group)group=await api.createWatchlist('默认自选');await api.addWatchlistMember(group.id,id);notice.value='已加入自选';emit('changed')}catch(e){notice.value=String(e)}finally{adding.value=''}}
onMounted(()=>void refresh());onBeforeUnmount(()=>{closed=true;clearTimeout(timer)});
</script>
<template><div class="sector-surface"><section class="sector-detail"><header><h2>{{sector?.name??id}}</h2><span>申万一级 · {{sectors?.asOf??'收盘数据'}}</span><UiButton icon="refresh" icon-only :disabled="loading||sectorUpdating" @click="refresh(true);refreshSectors(true)">刷新板块</UiButton></header><p v-if="sectorError" role="status">{{sectorError}}</p><div class="sector-values"><strong>{{fmt(sector?.close)}}</strong><span :class="tone(sector?.pct)">{{sector?.pct==null?'—':fmt(sector.pct)+'%'}}</span><span>成交额 {{sector?.amount==null?'—':fmt(sector.amount/1e8)+' 亿'}}</span></div>
<section class="sector-chart"><div class="chart-caption"><h3>指数收盘走势</h3><small v-if="history">{{history.items[0]?.date}} — {{history.asOf}}</small></div><p v-if="error" role="status">{{error}}</p><svg v-if="points" viewBox="0 0 1000 200" preserveAspectRatio="none" role="img" :aria-label="(sector?.name??id)+'指数走势'"><polyline :points="points" fill="none" stroke="var(--accent)" stroke-width="1.5" vector-effect="non-scaling-stroke"/></svg><p v-else>{{loading?'正在获取指数日线…':'暂无指数日线'}}</p><details v-if="history"><summary>每日行情</summary><div class="sector-table"><table><thead><tr><th>日期</th><th>开盘</th><th>最高</th><th>最低</th><th>收盘</th><th>涨跌幅</th></tr></thead><tbody><tr v-for="r in [...history.items].reverse()" :key="r.date"><td>{{r.date}}</td><td>{{fmt(r.open)}}</td><td>{{fmt(r.high)}}</td><td>{{fmt(r.low)}}</td><td>{{fmt(r.close)}}</td><td :class="tone(r.pct_chg)">{{r.pct_chg==null?'—':fmt(r.pct_chg)+'%'}}</td></tr></tbody></table></div></details></section>
<section class="sector-members"><div class="member-toolbar"><h3>当前成分股 <small>{{sector?.members.length??0}}</small></h3><select v-model="sort" aria-label="成分股排序" @change="page=1"><option value="pct">涨幅</option><option value="amount">成交额</option></select><input v-model="query" @input="page=1" placeholder="筛选名称或代码" aria-label="筛选成分股"/></div><p v-if="notice" role="status">{{notice}}</p><small>股票收盘 · {{breadth?.asOf??'暂无行情'}}</small><div class="sector-table"><table><thead><tr><th>股票</th><th>收盘</th><th>涨跌幅</th><th>成交额（亿）</th><th>自选</th></tr></thead><tbody><tr v-for="r in members.slice((page-1)*50,page*50)" :key="r.instrumentId"><td><button @click="emit('open',r.instrumentId)">{{r.name}}<small>{{r.instrumentId}}</small></button></td><td>{{fmt(r.quote?.close)}}</td><td :class="tone(r.quote?.pct)">{{r.quote==null?'—':fmt(r.quote.pct)+'%'}}</td><td>{{r.quote==null?'—':fmt(r.quote.amount/1e8)}}</td><td><UiButton icon="star" icon-only :disabled="!!adding" @click="add(r.instrumentId)">加入自选 {{r.name}}</UiButton></td></tr></tbody></table></div><p v-if="!members.length">{{sectorUpdating?'正在获取行业成分…':'没有匹配的成分股'}}</p><div v-if="members.length>50" class="pagination"><UiButton icon="chevron" :disabled="page<=1" @click="page--">上一页</UiButton><span>{{page}} / {{Math.ceil(members.length/50)}}</span><UiButton icon="chevron" :disabled="page*50>=members.length" @click="page++">下一页</UiButton></div></section>
</section></div></template>
<style scoped>
.sector-surface{container-type:inline-size}.sector-detail{padding:18px 24px;max-width:1400px;margin:auto}.sector-detail header,.chart-caption,.member-toolbar{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.sector-detail h2{font-size:18px;margin:0 auto 0 0}.sector-detail h3{font-size:13px;font-weight:500;margin:0 auto 0 0}.sector-detail small,.sector-detail header>span,.sector-detail p{color:var(--muted);font-size:12px}.sector-detail p{overflow-wrap:anywhere}.sector-values{display:flex;align-items:baseline;gap:18px;padding:20px 0;font-variant-numeric:tabular-nums}.sector-values strong{font-size:26px;font-weight:500}.sector-values>span:last-child{color:var(--muted);font-size:12px}.sector-chart{border-bottom:1px solid var(--line);padding:12px 0 20px}.sector-chart svg{height:190px;width:100%;margin-top:16px}.sector-chart summary{font-size:12px;color:var(--muted);cursor:pointer}.sector-members{padding-top:20px}.member-toolbar{margin-bottom:12px;gap:8px}.member-toolbar input,.member-toolbar select{min-height:28px;padding:4px 6px;font-size:12px}.member-toolbar input{width:145px}.sector-table{overflow:auto;max-height:500px;margin-top:12px}.sector-table table{width:100%;margin:0;white-space:nowrap;font-size:12px;font-variant-numeric:tabular-nums}.sector-table th{color:var(--muted);font-weight:400}.sector-table td,.sector-table th{text-align:right;padding:8px}.sector-table td:first-child,.sector-table th:first-child{text-align:left}.sector-table td:first-child button{text-align:left;padding:0}.sector-table td small{display:block;font-size:11px;margin-top:3px}.pagination{display:flex;justify-content:flex-end;align-items:center;gap:8px;margin-top:12px;font-size:12px}.rise{color:#ee8585!important}.fall{color:#64bca0!important}@container(max-width:550px){.sector-detail{padding:14px}.sector-values{gap:10px;flex-wrap:wrap}}
</style>
