<script setup lang="ts">
import {ref,computed} from 'vue';
import {useSectors} from './use-sectors';
import {marketNumber as fmt} from './use-market';
import UiButton from './UiButton.vue';
const props=defineProps<{colorMode:string;summary?:boolean}>();const emit=defineEmits<{open:[id:string,name:string]}>();
const {sectors,sectorError,sectorUpdating,refreshSectors}=useSectors();const sort=ref('up');
const rows=computed(()=>[...(sectors.value?.items??[])].sort((a,b)=>sort.value==='amount'?(b.amount??-Infinity)-(a.amount??-Infinity):sort.value==='down'?(a.pct??Infinity)-(b.pct??Infinity):(b.pct??-Infinity)-(a.pct??-Infinity)).slice(0,props.summary?6:100));
const tone=(n:number|null)=>n==null||n===0?'':((n>0)===(props.colorMode==='red-up')?'rise':'fall');
</script>
<template><section class="sector-list" :class="{summary}"><div class="sector-toolbar"><h3 v-if="summary">行业板块</h3><select v-model="sort" aria-label="行业排行排序"><option value="up">涨幅排行</option><option value="down">跌幅排行</option><option value="amount">成交额排行</option></select><UiButton icon="refresh" icon-only :disabled="sectorUpdating" @click="refreshSectors(true)">刷新行业</UiButton></div><p v-if="sectorError" role="status">{{sectorError}}</p><div class="sector-rows"><button v-for="r in rows" :key="r.id" @click="emit('open',r.id,r.name)"><span>{{r.name}}<small>{{r.members.length}} 只成分股</small></span><span :class="sort==='amount'?'':tone(r.pct)">{{sort==='amount'?(r.amount==null?'—':fmt(r.amount/1e8)+' 亿'):(r.pct==null?'—':fmt(r.pct)+'%')}}</span></button></div><p v-if="!rows.length">{{sectorUpdating?'正在获取行业行情…':'暂无行业行情'}}</p><footer><span v-if="sectorUpdating">正在更新 · </span>申万一级 · {{sectors?.asOf??'收盘数据'}}</footer></section></template>
<style scoped>
.sector-list{display:flex;flex-direction:column;min-height:0}.sector-toolbar{display:flex;gap:6px;align-items:center;padding:8px}.sector-toolbar select{min-width:0;flex:1;padding:5px 6px;height:28px}.sector-toolbar h3{font-size:13px;font-weight:500;margin:0 auto 0 0}.sector-rows{overflow:auto;min-height:0}.sector-rows>button{width:100%;display:flex;justify-content:space-between;align-items:center;text-align:left;padding:9px 12px;gap:8px;font-size:13px;border-radius:0}.sector-rows>button:hover{background:var(--raised)!important}.sector-rows small{display:block;margin-top:3px;color:var(--muted);font-size:11px}.sector-rows>button>span:last-child{flex:none;font-variant-numeric:tabular-nums}.sector-list p,.sector-list footer{font-size:12px;color:var(--muted);padding:8px 12px;margin:0;overflow-wrap:anywhere}.rise{color:#ee8585!important}.fall{color:#64bca0!important}.summary{padding:12px 0;border-bottom:1px solid var(--line)}.summary .sector-toolbar{padding:0 0 8px}.summary .sector-toolbar select{flex:none;width:100px}.summary .sector-rows{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 20px}.summary .sector-rows>button{padding-left:0;padding-right:0}.summary footer{padding-left:0}@container(max-width:500px){.summary .sector-rows{grid-template-columns:1fr}}
</style>
