<script setup lang="ts">
import UiButton from './UiButton.vue';
import {ref,computed,watch,onBeforeUnmount} from 'vue';
import type {FinancialData} from '../../../../packages/contracts/generated';
const props=defineProps<{ids:string[]}>();defineEmits<{open:[id:string]}>();
const endpoint=ref('income'),period=ref(''),data=ref<Record<string,FinancialData>>({}),names=ref<Record<string,string>>({}),busy=ref(false),error=ref('');let generation=0;
const fields:Record<string,[string,string][]>= {income:[['revenue','营业收入'],['n_income_attr_p','归母净利润']],balancesheet:[['total_assets','总资产'],['total_liab','总负债']],cashflow:[['n_cashflow_act','经营现金流净额']],daily_basic:[['close','收盘价'],['pe','PE'],['pe_ttm','PE TTM'],['pb','PB'],['total_mv','总市值']]};
const periods=computed(()=>[...new Set(Object.values(data.value).flatMap(d=>d.items.map((r:any)=>String(r.end_date??r.trade_date))))].sort().reverse());
function rows(id:string){return (data.value[id]?.items??[]).filter((r:any)=>String(r.end_date??r.trade_date)===period.value)}
function value(id:string,key:string){const matches=rows(id) as any[];return matches.length===1&&typeof matches[0][key]==='number'?matches[0][key].toLocaleString('zh-CN',{maximumFractionDigits:2}):'—'}
async function load(){if(!window.stock)return;const version=++generation;busy.value=true;error.value='';data.value={};try{const entries=await Promise.all(props.ids.map(async id=>{const [financial,stock]=await Promise.all([window.stock!.readFinancials(id,endpoint.value),window.stock!.searchInstruments(id,0)]);return {id,financial,name:stock.items.find(s=>s.id===id)?.name??id}}));if(version!==generation)return;for(const row of entries){data.value[row.id]=row.financial;names.value[row.id]=row.name}if(!periods.value.includes(period.value))period.value=periods.value[0]??''}catch(e){if(version===generation)error.value=e instanceof Error?e.message:String(e)}finally{if(version===generation)busy.value=false}}
watch(()=>[props.ids.join(','),endpoint.value],load,{immediate:true});onBeforeUnmount(()=>generation++);
</script>
<template><section class="stock-comparison"><header><h2>股票比较</h2><label>资料 <select v-model="endpoint" :disabled="busy"><option value="income">利润表</option><option value="balancesheet">资产负债表</option><option value="cashflow">现金流量表</option><option value="daily_basic">每日估值</option></select></label><label>同一期 <select v-model="period" :disabled="busy||!periods.length"><option v-for="date in periods" :key="date">{{date}}</option></select></label><UiButton icon="refresh" icon-only :disabled="busy" @click="load">刷新缓存数据</UiButton></header>
<p>仅比较所选 {{ids.length}} 只股票的本地资料。金额为元，PE/PB 为倍；财报为累计或期末数据。缺少该期或有多条披露时显示 —，不自动选择修订。不同公司会计口径仍需核对。</p><p v-if="busy" role="status">读取资料…</p><p v-if="error" role="alert">{{error}}</p>
<div class="comparison-table"><table><thead><tr><th>指标</th><th v-for="id in ids" :key="id"><UiButton icon="chevron" @click="$emit('open',id)">{{names[id]??id}}</UiButton><small>{{id}}</small></th></tr></thead><tbody><tr><th>该期资料</th><td v-for="id in ids" :key="id">{{rows(id).length===0?'缺少该期':rows(id).length>1?'多条披露，待核对':'1 条记录'}}</td></tr><tr v-for="[key,label] in fields[endpoint]" :key="key"><th>{{label}}</th><td v-for="id in ids" :key="id">{{value(id,key)}}</td></tr><tr v-if="endpoint!=='daily_basic'"><th>公告日</th><td v-for="id in ids" :key="id">{{rows(id).length===1?(rows(id)[0] as any).ann_date:'—'}}</td></tr></tbody></table></div>
<p v-if="!busy&&!periods.length">所选股票尚无此类资料。</p><details><summary>数据来源与版本</summary><p v-for="id in ids" :key="id">{{id}} · {{data[id]?.manifest?'Tushare · '+data[id].manifest?.asOf+' · '+data[id].manifest?.id:'无缓存快照'}}</p></details></section></template>
<style scoped>.stock-comparison{padding:20px 24px;min-width:0}.stock-comparison header{display:flex;gap:12px;flex-wrap:wrap;align-items:center}.stock-comparison h2{margin-right:auto}.stock-comparison p{color:var(--muted);font-size:0.923077rem;line-height:1.7;margin:16px 0}.comparison-table{overflow:auto}table{width:100%;border-collapse:collapse;min-width:500px}th,td{padding:12px;border-bottom:1px solid var(--line);text-align:left;font-variant-numeric:tabular-nums}small{display:block;color:var(--muted);margin-top:5px}.stock-comparison details{margin-top:20px;overflow-wrap:anywhere}</style>
