<script setup lang="ts">
import {ref,watch} from 'vue';
import Papa from 'papaparse';
import UiButton from './UiButton.vue';
import type {LedgerImportMapping,LedgerImportResult} from '../../../../packages/contracts/generated';
const fields:{id:keyof LedgerImportMapping;label:string}[]=[{id:'tradeId',label:'成交编号'},{id:'instrumentId',label:'股票代码'},{id:'date',label:'成交日期'},{id:'kind',label:'买卖方向'},{id:'quantity',label:'股数'},{id:'price',label:'成交价'},{id:'fee',label:'费用'}];
const input=ref<HTMLInputElement>(),csv=ref(''),filename=ref(''),headers=ref<string[]>([]),account=ref('manual'),mapping=ref<LedgerImportMapping>(Object.fromEntries(fields.map(f=>[f.id,f.id])) as unknown as LedgerImportMapping),result=ref<LedgerImportResult|null>(null),busy=ref(false),error=ref(''),page=ref(0);
watch([csv,account,mapping],()=>{result.value=null;page.value=0;error.value=''}, {deep:true,flush:'sync'});
async function select(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;result.value=null;error.value='';try{if(file.size>1048576)throw Error('CSV 上限为 1 MB。');const text=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer());const parsed=Papa.parse<string[]>(text,{preview:1,skipEmptyLines:true});if(parsed.errors.length||!parsed.data[0]?.length)throw Error('CSV 表头无法读取。');csv.value=text;headers.value=parsed.data[0];filename.value=file.name;mapping.value=Object.fromEntries(fields.map(f=>[f.id,headers.value.includes(f.id)?f.id:''])) as unknown as LedgerImportMapping}catch{csv.value='';filename.value='';headers.value=[];error.value='无法读取文件，请选择 1 MB 以内的 UTF-8 CSV。'}finally{if(input.value)input.value.value=''}}
async function run(commit=false){if(busy.value||!window.stock)return;busy.value=true;error.value='';try{result.value=await window.stock.importLedger({csv:csv.value,mapping:{...mapping.value},account:account.value,commit,previewToken:commit?result.value?.previewToken??null:null});page.value=0}catch(e){result.value=null;error.value=String(e).replace(/^Error invoking remote method[^:]*:\s*Error:\s*/,'')}finally{busy.value=false}}
async function template(){try{await window.stock?.exportLedgerTemplate()}catch{error.value="模板未能保存，请重试。"}}
</script>
<template><details class="trade-import"><summary>导入成交记录</summary><div class="import-body"><div class="import-toolbar"><input ref="input" class="file-input" type="file" accept=".csv,text/csv" :disabled="busy" @change="select"><UiButton icon="upload" :disabled="busy" @click="input?.click()">选择 CSV</UiButton><UiButton icon="download" @click="template">下载模板</UiButton><span>{{filename}}</span></div><fieldset :disabled="busy"><label>账本标识<input v-model="account" maxlength="80" aria-label="导入账本标识"></label><div v-if="headers.length" class="import-mapping"><label v-for="field in fields" :key="field.id">{{field.label}}<select v-model="mapping[field.id]"><option value="" disabled>选择列</option><option v-for="header in headers" :key="header" :value="header">{{header}}</option></select></label></div></fieldset><p v-if="csv" class="import-hint">日期 YYYY-MM-DD · 方向 buy/sell · 代码含交易所后缀 · 费用为 0 时请填 0</p><UiButton v-if="csv" icon="search" :disabled="busy||fields.some(f=>!mapping[f.id])" @click="run()">预览导入</UiButton><p v-if="error" role="alert">{{error}}</p><template v-if="result"><div class="import-result" role="status">{{result.committed?'已导入':'待导入'}} {{result.ready}} 条 · 已存在 {{result.duplicates}} 条 · 错误 {{result.errors}} 条<UiButton v-if="!result.committed&&!result.errors&&result.ready" icon="check" :disabled="busy" @click="run(true)">确认导入</UiButton></div><div class="import-table"><table><thead><tr><th>行</th><th>成交编号</th><th>股票</th><th>日期</th><th>方向</th><th>股数</th><th>成交价</th><th>费用</th><th>状态</th></tr></thead><tbody><tr v-for="row in result.rows.slice(page*50,(page+1)*50)" :key="row.line"><td>{{row.line}}</td><td>{{row.tradeId}}</td><td>{{row.instrumentId}}</td><td>{{row.date}}</td><td>{{row.kind==='buy'?'买入':row.kind==='sell'?'卖出':row.kind}}</td><td>{{row.quantity}}</td><td>{{row.price}}</td><td>{{row.fee}}</td><td :class="{invalid:row.status==='error'}">{{row.message||(result.committed?'已导入':'可导入')}}</td></tr></tbody></table></div><div v-if="result.rows.length>50" class="import-toolbar"><UiButton :disabled="page===0" @click="page--">上一页</UiButton><span>{{page+1}} / {{Math.ceil(result.rows.length/50)}}</span><UiButton :disabled="(page+1)*50>=result.rows.length" @click="page++">下一页</UiButton></div></template></div></details></template>
<style scoped>.trade-import{margin-top:20px;border-top:1px solid var(--line);padding-top:16px}summary{cursor:pointer}.import-body{padding-top:12px}.import-toolbar,.import-result{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.file-input{display:none}fieldset{border:0;margin:12px 0;padding:0;min-width:0}label{display:flex;flex-direction:column;gap:6px;font-size:12px;width:160px;max-width:100%}.import-mapping{display:flex;flex-wrap:wrap;gap:12px;margin-top:12px}.import-hint,.import-toolbar>span{color:var(--muted);font-size:12px}.import-result{margin:16px 0}.import-table{max-height:360px;overflow:auto}table{border-collapse:collapse;width:100%;font-size:12px}th,td{text-align:left;padding:9px;border-bottom:1px solid var(--line);overflow-wrap:anywhere}th{position:sticky;top:0;background:var(--surface)}.invalid,[role=alert]{color:var(--danger)}</style>
