export interface CodexAccountStatus {connected:boolean;pending:boolean;model:string;models:{id:string;name:string;isDefault:boolean}[];error:string;mode?:'chatgpt'|'api'|'custom'}
import type {ServiceState,ServiceStatus,Settings,Overview,Watchlist,JobEvent,JobEventPage,Instrument,Adjustment,Bar,BarPage,BarVersion,FinancialData,FinancialVersion,ScreenCondition,ScreenPage,InstrumentPage,Diagnostic,Job,ScreenPoolPlan,ScreenBatch,RecapReport,RecapResult,ModelRecapPolicy,ModelRecapUsage,ModelRecapAttempt,ModelRecapContent,ResearchContext,ResearchEntry,ResearchReport,RpcMetadata} from './generated';
export type {ServiceState,ServiceStatus,Settings,Overview,Watchlist,JobEvent,JobEventPage,Instrument,Adjustment,Bar,BarPage,BarVersion,FinancialData,FinancialVersion,ScreenCondition,ScreenPage,InstrumentPage,Diagnostic,Job,ScreenPoolPlan,ScreenBatch,RecapReport,RecapResult,ModelRecapPolicy,ModelRecapUsage,ModelRecapAttempt,ModelRecapContent,ResearchContext,ResearchEntry,ResearchReport,RpcMetadata} from './generated';
export interface ModelRecapInfo {policy:ModelRecapPolicy;usage:ModelRecapUsage;attempt:ModelRecapAttempt;status:{state:string;message:string};quote:{reservedMicroUsd:number;maxOutputTokens:number;priceCheckedAt:string}|null;priceError:string;model:string}
export interface ModelRecapReport {date:string;model:string;estimatedMicroUsd:number|null;reservedMicroUsd:number;report:ModelRecapContent;facts:{id:string;value:number;unit:string;date:string}[]}
export interface UpdateStatus {repo:string;current:string;state:string;version:string|null;notes:string;received:number;total:number;message:string}
export type DesktopResearchReport = ResearchReport & {provenance:RpcMetadata & {requestId:string}};
export interface ProviderSettings {name:string;baseUrl:string;model:string;apiKey:string}
export interface ProviderStatus {name:string;baseUrl:string;model:string;configured:boolean;hasKey:boolean;encrypted:boolean}
export interface DesktopBridge {
  copilotTools(threadId:string,cursor?:string|null):Promise<{data:{name:string;runtimeStatus:string|null;authStatus:string;toolCount:number;discoveryFailed:boolean}[];nextCursor:string|null}>;
  nativeMcpRead():Promise<{project:string;file:string|null;version:string|null;servers:{name:string;enabled:boolean;effectiveEnabled:boolean|null;type:string}[]}>;
  nativeMcpWrite(value:Record<string,unknown>):Promise<Awaited<ReturnType<DesktopBridge['nativeMcpRead']>>&{status:string}>;
  openManagedLocation(target:'config'|'project'|'data'):Promise<void>;
  nativeConfigRead():Promise<{project:string;file:string|null;version:string|null;values:Record<string,{value:string|null;userValue:string|null;origin:string}>}>;
  nativeConfigWrite(value:{key:string;value:string;project:string;version:string}):Promise<Awaited<ReturnType<DesktopBridge['nativeConfigRead']>>&{status:string}>;
  stockToolsStatus():Promise<{enabled:boolean;serviceState:string;mcpAvailable:boolean;cliAvailable:boolean;tools:{name:string;description:string}[]}>;
  saveStockTools(enabled:boolean):Promise<{enabled:boolean}>;
  windowZoom():Promise<number>;
  setWindowZoom(value:number):Promise<number>;
  checkProvider():Promise<{completed:boolean;model:string;text:string}>;
  providerStatus():Promise<ProviderStatus>;
  saveProvider(value:Omit<ProviderSettings,'apiKey'>&{apiKey:string|null}):Promise<ProviderStatus>;
  copilotPolicy():Promise<{networkAccess:boolean;mode:'ask'|'auto-review'|'full-access'}>;
  saveCopilotPolicy(value:{networkAccess:boolean;mode:'ask'|'auto-review'|'full-access'}):Promise<{networkAccess:boolean;mode:'ask'|'auto-review'|'full-access'}>;
  codexSandboxStatus():Promise<{readiness:string;mode:string|null}>;
  codexSandboxSetup(mode:'elevated'|'unelevated'):Promise<{readiness:string;mode:string|null}>;
  holdings():Promise<import('./generated').Holding[]>;
  latestQuotes(instrumentIds:string[]):Promise<import('./generated').LatestQuote[]>;
  holdingsSummary():Promise<import('./generated').HoldingsSummary>;
  saveHolding(params:import('./generated').HoldingSaveRequest):Promise<import('./generated').Holding>;
  dataPolicy():Promise<import('./generated').DemandPolicy>;
  configureData(value:import('./generated').DemandPolicy):Promise<import('./generated').DemandPolicy>;
  ensureData(value:{instrumentId:string;endpoint:'bars'|'daily_basic'|'income'|'balancesheet'|'cashflow';years:1|3|4;force:boolean}):Promise<import('./generated').DemandState>;
  projectSearch(query:string):Promise<{entries:{name:string;path:string;directory:boolean;link:boolean}[];truncated:boolean}>;
  projectManage(value:{action:'file'|'folder'|'rename';path:string;name:string}):Promise<{path:string}>;
  projectReveal(path:string):Promise<void>;
  projectImage(path:string):Promise<string>;
  projectList(path:string):Promise<{path:string;entries:{name:string;path:string;directory:boolean;link:boolean}[];truncated:boolean}>;
  projectRead(path:string):Promise<{path:string;text:string;revision:string;modifiedAt:string}>;
  projectWrite(path:string,text:string,revision:string):Promise<{path:string;text:string;revision:string;modifiedAt:string;backup:string}>;
  copilotProject():Promise<{path:string;state:string}>;
  copilotSelectProject():Promise<{path:string;state:string}>;
  copilotList(cursor?:string|null):Promise<any>;
  copilotCreate():Promise<any>;
  copilotRead(threadId:string,cursor?:string|null):Promise<any>;
  providerModels():Promise<any>;
  copilotModels():Promise<any>;
  copilotAttachments():Promise<{id:string;name:string}[]>;
  copilotSend(threadId:string,text:string,options?:{mode?:'default'|'plan';model?:string;effort?:string;attachments?:string[];permissionMode?:'ask'|'auto-review'|'full-access'}):Promise<any>;
  schedulerList():Promise<any>;
  schedulerSave(task:any):Promise<any>;
  schedulerRemove(id:string):Promise<void>;
  schedulerRun(id:string):Promise<any>;
  schedulerOpen(threadId:string):Promise<void>;
  onSchedulerChanged(listener:()=>void):()=>void;
  copilotGoal(threadId:string,change?:{clear?:true;objective?:string;status?:'active'|'paused';tokenBudget?:number|null}):Promise<any>;
  copilotInterrupt(threadId:string):Promise<{interrupted:boolean}>;
  copilotAnswer(id:string|number,answers:Record<string,string[]>):Promise<void>;
  copilotApprove(id:string|number,decision:'accept'|'acceptForSession'|'decline'|'cancel'):Promise<void>;
  onCopilotEvent(listener:(event:any)=>void):()=>void;
  windowCloseBehavior(value?:'ask'|'background'|'quit'):Promise<'ask'|'background'|'quit'>;
  windowCloseChoice(choice:'background'|'quit'|'cancel',remember?:boolean):Promise<void>;
  onWindowCloseRequest(listener:()=>void):()=>void;
  windowAction(action:'minimize'|'maximize'|'close'):Promise<void>;
  readSectors():Promise<import('./generated').SectorSnapshot|null>;
  ensureSectors(force:boolean):Promise<import('./generated').DemandState>;
  readSectorHistory(sectorId:string):Promise<import('./generated').SectorHistory|null>;
  ensureSectorHistory(sectorId:string,force:boolean):Promise<import('./generated').DemandState>;
  readBreadth():Promise<import('./generated').BreadthSnapshot|null>;
  ensureBreadth(force:boolean):Promise<import('./generated').DemandState>;
  readIndex(indexId:import('./generated').IndexId):Promise<import('./generated').IndexSnapshot|null>;
  readMarket(marketId:import('./generated').MarketId):Promise<import('./generated').MarketSnapshot|null>;
  syncIndex(indexId:import('./generated').IndexId,start:string,end:string):Promise<import('./generated').IndexSnapshot>;
  syncMarket(marketId:import('./generated').MarketId,start:string,end:string):Promise<import('./generated').MarketSnapshot>;
  windowDraftGuard(blocked:boolean):Promise<void>;
  windowMaximized():Promise<boolean>;
  onWindowMaximized(listener:(maximized:boolean)=>void):()=>void;
  updateStatus():Promise<UpdateStatus>;
  configureUpdates(repo:string):Promise<UpdateStatus>;
  checkUpdates():Promise<UpdateStatus>;
  downloadUpdate():Promise<UpdateStatus>;
  cancelUpdate():Promise<UpdateStatus>;
  installUpdate():Promise<UpdateStatus>;
  recapStatus():Promise<{state:string;message:string;checkedAt:string|null}>;
  modelRecapInfo():Promise<ModelRecapInfo>;
  configureModelRecap(p:ModelRecapPolicy):Promise<unknown>;
  startModelRecap():Promise<unknown>;
  stopModelRecap():Promise<unknown>;
  latestModelRecap():Promise<ModelRecapReport|null>;
  recapPolicy():Promise<{enabled:boolean}>;
  configureRecap(enabled:boolean):Promise<{enabled:boolean}>;
  latestRecap():Promise<RecapReport|null>;
  generateRecap():Promise<RecapResult>;
  createBackup():Promise<{completed:boolean;bytes?:number;files?:number}>;
  restoreBackup():Promise<{completed:boolean;originalPreserved?:boolean}>;
  profileLocation():Promise<{path:string;migration:{state:string;message:string}}>;
  migrateProfile():Promise<{completed:boolean;files?:number;bytes?:number;originalPreserved?:boolean;journalWarning?:boolean}>;
  compactSnapshots():Promise<{converted:number;bundles:number;alreadyBundled:number;retainedOriginals:boolean}>;
  accountStatus():Promise<CodexAccountStatus>;
  accountRefresh():Promise<CodexAccountStatus>;
  accountLogin():Promise<CodexAccountStatus>;
  accountCancel():Promise<CodexAccountStatus>;
  accountLogout():Promise<CodexAccountStatus>;
  accountModel(model:string):Promise<CodexAccountStatus>;
  accountMode(mode:'chatgpt'|'api'|'custom'):Promise<CodexAccountStatus>;
  modelStatus():Promise<{configured:boolean;model:string;encrypted:boolean}>;
  saveModel(model:string,apiKey:string):Promise<{configured:boolean;model:string;encrypted:boolean}>;
  prepareResearch(instrumentIds:string[],question:string,requestKey:string):Promise<ResearchContext>;
  researchEvents(runId:string,after:number):Promise<{items:{sequence:number;stage:string;createdAt:string}[];nextCursor:number;state:string}>;
  startResearch(runId:string):Promise<{runId:string;state:string}>;
  cancelResearch(runId:string):Promise<{runId:string;state:string}>;
  researchStatus():Promise<{runId:string;stage:string}|null>;
  researchList(offset:number):Promise<{items:ResearchEntry[];total:number}>;
  researchReport(runId:string):Promise<DesktopResearchReport>;
  researchContext(runId:string):Promise<ResearchContext>;
  researchDraft(runId:string):Promise<{draftId:string;payload:{runId:string;report:{summary:string;claims:{text:string;factIds:string[];values?:{factId:string;value:number;unit:string;date:string}[]}[];limitations:string[]}}}>;
  researchChart(runId:string,instrumentId:string):Promise<{artifactId:string;snapshotId:string;asOf:string;svg:string;rows:number}>;
  exportResearch(runId:string):Promise<{saved:boolean}>;
  overview(): Promise<Overview>;
  watchlists(): Promise<Watchlist[]>;
  createWatchlist(name: string): Promise<Watchlist>;
  renameWatchlist(listId:string,name:string):Promise<Watchlist>;
  watchlistMembers(listId:string):Promise<Instrument[]>;
  addWatchlistMember(listId:string,instrumentId:string):Promise<Instrument[]>;
  removeWatchlistMember(listId:string,instrumentId:string):Promise<Instrument[]>;
  reorderWatchlist(listId:string,ids:string[]):Promise<Instrument[]>;
  saveSettings(settings: Settings): Promise<Settings>;
  credentialStatus(): Promise<{ configured: boolean; encrypted: boolean }>;
  saveTushareToken(token: string): Promise<{ configured: boolean; encrypted: boolean }>;
  diagnoseTushare(endpoint:string): Promise<Diagnostic>;
  syncCatalog(exchange:string,status:string):Promise<{state:string;rows:number;message:string}>;
  syncCalendar(exchange:string,year:number):Promise<{state:string;rows:number;message:string}>;
  searchInstruments(query:string,offset:number):Promise<InstrumentPage>;
  syncBars(instrumentId:string,start:string,end:string):Promise<{snapshotId:string;rows:number;asOf:string;reused:boolean}>;
  barVersions(instrumentId:string):Promise<BarVersion[]>;
  readBars(snapshotId:string,adjustment:Adjustment,offset:number):Promise<BarPage>;
  syncFinancials(instrumentId:string,endpoint:string,start:string,end:string):Promise<{snapshotId:string;rows:number;asOf:string}>;
  readFinancials(instrumentId:string,endpoint:string,snapshotId?:string):Promise<FinancialData>;
  financialSnapshots(instrumentId:string,endpoint:string):Promise<FinancialVersion[]>;
  jobs():Promise<Job[]>;
  jobEvents(after:number):Promise<JobEventPage>;
  autoSyncStatus():Promise<{state:string;message:string}>;
  autoSyncPolicy():Promise<{enabled:boolean}>;
  configureAutoSync(enabled:boolean):Promise<{enabled:boolean}>;
  retryJob(id:string):Promise<{completed:boolean}>;
  cancelJob(id:string):Promise<Job>;
  runScreen(date:string,conditions:ScreenCondition[],sort:string,direction:string):Promise<ScreenPage>;
  screenPage(resultId:string,offset:number):Promise<ScreenPage>;
  latestScreen():Promise<ScreenPage|null>;
  prepareScreenPool(params:{scope:'all'|'watchlist';listId:string|null;date:string;lookback:number}):Promise<ScreenPoolPlan>;
  startScreenBatch(planId:string):Promise<ScreenBatch>;
  screenBatchStatus():Promise<ScreenBatch|null>;
  pauseScreenBatch():Promise<ScreenBatch|null>;
  saveScreen(name:string,conditions:ScreenCondition[]):Promise<{name:string;conditions:ScreenCondition[]}[]>;
  screenDefinitions():Promise<{name:string;conditions:ScreenCondition[]}[]>;
  serviceStatus(): Promise<ServiceStatus>;
  retryService(): Promise<ServiceStatus>;
  onServiceStatus(listener: (status: ServiceStatus) => void): () => void;
}
declare global { interface Window { stock?: DesktopBridge } }


