// Generated by scripts/generate-contracts.mjs. Edit schema.json.
export type ReferenceEndpoint = "stock_company" | "namechange" | "stk_managers" | "stk_rewards" | "stk_premarket" | "stock_st" | "st" | "stock_hsgt" | "bse_mapping" | "new_share" | "bak_basic" | "forecast" | "express" | "fina_indicator" | "fina_mainbz";
export interface ReferenceColumn {
  key: string;
  label: string;
}
export interface ReferenceDataset {
  endpoint: ReferenceEndpoint;
  name: string;
  mode: string;
  columns: Array<ReferenceColumn>;
}
export type ReferenceCatalog = Array<ReferenceDataset>;
export interface ReferenceParams {
  endpoint: ReferenceEndpoint;
  instrumentId: string;
  start: string;
  end: string;
}
export interface ReferenceSyncRequest {
  endpoint: ReferenceEndpoint;
  instrumentId: string;
  start: string;
  end: string;
  token: string;
}
export interface ReferenceReadRequest {
  endpoint: ReferenceEndpoint;
  instrumentId: string;
  start: string;
  end: string;
  offset: number;
}
export interface ReferenceSnapshot {
  endpoint: ReferenceEndpoint;
  instrumentId: string;
  start: string;
  end: string;
  columns: Array<ReferenceColumn>;
  rows: Array<Array<string | number | null>>;
  snapshotId: string;
  collectedAt: string;
  provider: "tushare";
}
export interface ReferencePageData {
  endpoint: ReferenceEndpoint;
  instrumentId: string;
  start: string;
  end: string;
  columns: Array<ReferenceColumn>;
  rows: Array<Array<string | number | null>>;
  snapshotId: string;
  collectedAt: string;
  provider: "tushare";
  total: number;
  offset: number;
}
export type ReferencePage = ReferencePageData | null;
export interface ReferenceSyncResult {
  snapshotId: string;
  rows: number;
}
export interface ReferenceJobRequest {
  kind: "reference.sync";
  params: ReferenceParams;
  token: string;
}
export interface LedgerBalanceEvent {
  kind: "opening" | "balance";
  date: string;
  quantity: number;
  price: string | null;
}
export interface LedgerTradeEvent {
  kind: "buy" | "sell";
  date: string;
  quantity: number;
  price: string;
  fee: string;
}
export type LedgerEvent = LedgerBalanceEvent | LedgerTradeEvent;
export interface LedgerWriteRequest {
  instrumentId: string;
  requestId: string;
  revision: number;
  event: LedgerEvent | null;
  supersedes: string | null;
  voided: boolean;
}
export interface LedgerWriteResult {
  eventId: string;
  revision: number;
  quantity: number;
  costBasis: string | null;
  averageCost: string | null;
  realizedProfit: string | null;
}
export interface LedgerReadRequest {
  instrumentId: string;
}
export interface LedgerRecord {
  id: string;
  event: LedgerEvent;
  supersedes: string | null;
  voided: boolean;
  active: boolean;
  source: string;
  createdAt: string;
}
export interface LedgerReadResult {
  instrumentId: string;
  revision: number;
  quantity: number;
  costBasis: string | null;
  averageCost: string | null;
  realizedProfit: string | null;
  events: Array<LedgerRecord>;
}
export interface AnnouncementRow {
  id: string;
  instrumentId: string;
  date: string;
  title: string;
  url: string;
  publishedAt: string | null;
}
export interface AnnouncementReadRequest {
  instrumentId: string;
  offset: number;
}
export interface AnnouncementSyncParams {
  instrumentId: string;
  start: string;
  end: string;
}
export interface AnnouncementPage {
  snapshotId: string | null;
  instrumentId: string;
  start: string | null;
  end: string | null;
  collectedAt: string | null;
  total: number;
  offset: number;
  items: Array<AnnouncementRow>;
}
export interface AnnouncementSyncRequest {
  instrumentId: string;
  start: string;
  end: string;
  token: string;
}
export interface AnnouncementSyncResult {
  snapshotId: string;
  rows: number;
}
export interface AnnouncementJobRequest {
  kind: "announcements.sync";
  params: AnnouncementSyncParams;
  token: string;
}
export interface BreadthRow {
  instrumentId: string;
  name: string;
  close: number;
  pct: number;
  amount: number;
  volume: number;
  limitUp: boolean | null;
  limitDown: boolean | null;
}
export interface BreadthSnapshot {
  snapshotId: string;
  asOf: string;
  collectedAt: string;
  items: Array<BreadthRow>;
  limitsAvailable: boolean;
}
export type BreadthReadResult = BreadthSnapshot | null;
export interface BreadthSyncJobParams {
  date: string;
}
export interface BreadthSyncJobRequest {
  kind: "breadth.sync";
  token: string;
  params: BreadthSyncJobParams;
}
export interface MarketEnsureRequest {
  token: string;
  force: boolean;
}
export type MarketId = "SH_A" | "SZ_A" | "SH_STAR" | "SZ_GEM" | "SZ_STOCK";
export interface MarketRow {
  date: string;
  com_count: number | null;
  total_share: number | null;
  float_share: number | null;
  total_mv: number | null;
  float_mv: number | null;
  amount: number | null;
  vol: number | null;
  trans_count: number | null;
  pe: number | null;
  tr: number | null;
}
export interface MarketSnapshot {
  snapshotId: string;
  marketId: MarketId;
  name: string;
  endpoint: "daily_info" | "sz_daily_info";
  provider: "tushare";
  collectedAt: string;
  asOf: string;
  start: string;
  end: string;
  items: Array<MarketRow>;
}
export type OptionalMarketSnapshot = MarketSnapshot | null;
export interface MarketLatestRequest {
  marketId: MarketId;
}
export interface MarketVersionRequest {
  marketId: MarketId;
  snapshotId: string;
}
export type MarketReadRequest = MarketLatestRequest | MarketVersionRequest;
export interface MarketSyncJobParams {
  marketId: MarketId;
  start: string;
  end: string;
}
export interface MarketSyncRequest {
  token: string;
  marketId: MarketId;
  start: string;
  end: string;
}
export interface MarketSyncJobRequest {
  kind: "market.sync";
  token: string;
  params: MarketSyncJobParams;
}
export type IndexId = "000001.SH" | "399001.SZ" | "399006.SZ" | "000300.SH";
export interface IndexRow {
  date: string;
  open: number;
  high: number;
  low: number;
  close: number;
  pre_close: number | null;
  change: number | null;
  pct_chg: number | null;
  volume: number | null;
  amount: number | null;
}
export interface IndexSnapshot {
  snapshotId: string;
  indexId: IndexId;
  name: string;
  provider: "tushare";
  collectedAt: string;
  asOf: string;
  start: string;
  end: string;
  items: Array<IndexRow>;
}
export type OptionalIndexSnapshot = IndexSnapshot | null;
export interface IndexLatestRequest {
  indexId: IndexId;
}
export interface IndexVersionRequest {
  indexId: IndexId;
  snapshotId: string;
}
export type IndexReadRequest = IndexLatestRequest | IndexVersionRequest;
export interface IndexSyncJobParams {
  indexId: IndexId;
  start: string;
  end: string;
}
export interface IndexSyncRequest {
  token: string;
  indexId: IndexId;
  start: string;
  end: string;
}
export interface IndexSyncJobRequest {
  kind: "index.sync";
  token: string;
  params: IndexSyncJobParams;
}
export type ServiceState = "starting" | "ready" | "failed" | "stopped" | "stopping";
export interface ServiceStatus {
  state: ServiceState;
  message: string;
  restarts: number;
  maintenance?: boolean;
}
export interface Settings {
  colorMode: "red-up" | "green-up";
  closeToTray: boolean;
}
export interface Overview {
  protocolVersion: 2;
  schemaVersion: number;
  instruments: number;
  watchlists: number;
  jobs: number;
  reports: number;
  settings: Settings;
  dataAsOf: string | null;
}
export interface Watchlist {
  id: string;
  name: string;
  count: number;
  createdAt: string;
}
export interface JobEvent {
  sequence: number;
  jobId: string;
  generation: number;
  event: string;
  state: string;
  createdAt: string;
}
export interface JobEventPage {
  profileId: string;
  items: Array<JobEvent>;
  nextAfter: number;
  hasMore: boolean;
}
export interface JobEventRequest {
  after: number;
}
export type WatchlistList = Array<Watchlist>;
export interface Instrument {
  id: string;
  name: string;
  exchange: string;
  listStatus: string;
  listDate: string | null;
  delistDate: string | null;
}
export type InstrumentList = Array<Instrument>;
export interface WatchlistCreateRequest {
  name: string;
}
export interface WatchlistMembersRequest {
  listId: string;
}
export interface WatchlistChangeRequest {
  listId: string;
  instrumentId: string;
}
export interface WatchlistReorderRequest {
  listId: string;
  ids: Array<string>;
}
export type Adjustment = "none" | "forward" | "backward";
export interface Bar {
  instrumentId: string;
  date: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  amount: number;
}
export interface BarUnits {
  price: "CNY";
  volume: "shares";
  amount: "CNY";
}
export interface BarPage {
  snapshotId: string;
  items: Array<Bar>;
  total: number;
  offset: number;
  asOf: string;
  provider: "tushare";
  adjustment: Adjustment;
  anchor: string | null;
  factorVersion: string;
  units: BarUnits;
}
export interface BarVersion {
  snapshotId: string;
  asOf: string;
  collectedAt: string;
  rows: number;
}
export type BarVersionList = Array<BarVersion>;
export interface BarReadRequest {
  snapshotId: string;
  adjustment: Adjustment;
  offset: number;
}
export interface BarVersionsRequest {
  instrumentId: string;
}
export type FinancialEndpoint = "income" | "balancesheet" | "cashflow" | "daily_basic";
export interface FinancialReadRequest {
  instrumentId: string;
  endpoint: FinancialEndpoint;
  snapshotId?: string;
}
export interface FinancialVersionsRequest {
  instrumentId: string;
  endpoint: FinancialEndpoint;
}
export interface FinancialVersion {
  snapshotId: string;
  collectedAt: string;
  asOf: string;
  rows: number;
  start: string;
  end: string;
}
export type FinancialVersionList = Array<FinancialVersion>;
export interface IncomeUnits {
  revenue: "CNY";
  n_income_attr_p: "CNY";
}
export interface IncomeSourceRequest {
  ts_code: string;
  start_date: string;
  end_date: string;
  report_type: "1";
}
export interface IncomeGrowth {
  revenue: number | null;
  n_income_attr_p: number | null;
}
export interface IncomeRow {
  ts_code: string;
  ann_date: string;
  f_ann_date: string | null;
  end_date: string;
  report_type: "1";
  comp_type: "1" | "2" | "3" | "4" | "7";
  revisionCount: number;
  revenue: number | null;
  n_income_attr_p: number | null;
  yoy: IncomeGrowth;
}
export interface IncomeManifest {
  id: string;
  endpoint: "income";
  instrumentId: string;
  provider: "tushare";
  request: IncomeSourceRequest;
  collectedAt: string;
  rows: number;
  asOf: string;
  units: IncomeUnits;
  basis: "consolidated cumulative; balance sheet point-in-time";
  strictPointInTime: false;
}
export interface IncomeData {
  manifest: IncomeManifest;
  items: Array<IncomeRow>;
}
export interface BalanceUnits {
  total_assets: "CNY";
  total_liab: "CNY";
}
export interface BalanceSourceRequest {
  ts_code: string;
  start_date: string;
  end_date: string;
  report_type: "1";
}
export interface BalanceGrowth {
  total_assets: number | null;
  total_liab: number | null;
}
export interface BalanceRow {
  ts_code: string;
  ann_date: string;
  f_ann_date: string | null;
  end_date: string;
  report_type: "1";
  comp_type: "1" | "2" | "3" | "4" | "7";
  revisionCount: number;
  total_assets: number | null;
  total_liab: number | null;
  yoy: BalanceGrowth;
}
export interface BalanceManifest {
  id: string;
  endpoint: "balancesheet";
  instrumentId: string;
  provider: "tushare";
  request: BalanceSourceRequest;
  collectedAt: string;
  rows: number;
  asOf: string;
  units: BalanceUnits;
  basis: "consolidated cumulative; balance sheet point-in-time";
  strictPointInTime: false;
}
export interface BalanceData {
  manifest: BalanceManifest;
  items: Array<BalanceRow>;
}
export interface CashflowUnits {
  n_cashflow_act: "CNY";
}
export interface CashflowSourceRequest {
  ts_code: string;
  start_date: string;
  end_date: string;
  report_type: "1";
}
export interface CashflowGrowth {
  n_cashflow_act: number | null;
}
export interface CashflowRow {
  ts_code: string;
  ann_date: string;
  f_ann_date: string | null;
  end_date: string;
  report_type: "1";
  comp_type: "1" | "2" | "3" | "4" | "7";
  revisionCount: number;
  n_cashflow_act: number | null;
  yoy: CashflowGrowth;
}
export interface CashflowManifest {
  id: string;
  endpoint: "cashflow";
  instrumentId: string;
  provider: "tushare";
  request: CashflowSourceRequest;
  collectedAt: string;
  rows: number;
  asOf: string;
  units: CashflowUnits;
  basis: "consolidated cumulative; balance sheet point-in-time";
  strictPointInTime: false;
}
export interface CashflowData {
  manifest: CashflowManifest;
  items: Array<CashflowRow>;
}
export interface ValuationUnits {
  close: "CNY";
  pe: "ratio";
  pe_ttm: "ratio";
  pb: "ratio";
  total_mv: "CNY";
  circ_mv: "CNY";
}
export interface ValuationSourceRequest {
  ts_code: string;
  start_date: string;
  end_date: string;
}
export interface ValuationRow {
  ts_code: string;
  trade_date: string;
  close: number | null;
  pe: number | null;
  pe_ttm: number | null;
  pb: number | null;
  total_mv: number | null;
  circ_mv: number | null;
}
export interface ValuationManifest {
  id: string;
  endpoint: "daily_basic";
  instrumentId: string;
  provider: "tushare";
  request: ValuationSourceRequest;
  collectedAt: string;
  rows: number;
  asOf: string;
  units: ValuationUnits;
  basis: "daily";
  strictPointInTime: false;
}
export interface ValuationData {
  manifest: ValuationManifest;
  items: Array<ValuationRow>;
}
export interface EmptyFinancialData {
  manifest: null;
  items: Array<null>;
}
export type FinancialData = EmptyFinancialData | IncomeData | BalanceData | CashflowData | ValuationData;
export type ScreenField = "price" | "amount" | "total_mv" | "pe" | "pb" | "ma20Ratio" | "ma60Ratio";
export type ScreenSort = "id" | "price" | "amount" | "total_mv" | "pe" | "pb" | "ma20Ratio" | "ma60Ratio";
export type SortDirection = "asc" | "desc";
export interface ScreenCondition {
  field: ScreenField;
  operator: "gt" | "gte" | "lt" | "lte";
  value: number;
}
export type ScreenConditions = Array<ScreenCondition>;
export interface ScreenRow {
  id: string;
  name: string;
  date: string;
  price: number;
  amount: number;
  total_mv: number | null;
  pe: number | null;
  pb: number | null;
  ma20Ratio: number | null;
  ma60Ratio: number | null;
}
export interface ScreenPage {
  resultId: string;
  date: string;
  conditions: ScreenConditions;
  sort: ScreenSort;
  direction: SortDirection;
  items: Array<ScreenRow>;
  total: number;
  covered: number;
  missingDate: number;
  catalogCount: number;
  offset: number;
}
export interface ScreenRunRequest {
  date: string;
  conditions: ScreenConditions;
  sort: ScreenSort;
  direction: SortDirection;
}
export interface ScreenPageRequest {
  resultId: string;
  offset: number;
}
export interface ScreenDefinition {
  name: string;
  conditions: ScreenConditions;
}
export type ScreenDefinitions = Array<ScreenDefinition>;
export type LatestScreen = ScreenPage | null;
export interface NoParams {
}
export type Exchange = "SSE" | "SZSE" | "BSE";
export interface CatalogSyncRequest {
  token: string;
  exchange: Exchange;
  status: "L" | "D" | "P";
}
export interface CalendarSyncRequest {
  token: string;
  exchange: "SSE" | "SZSE";
  year: number;
}
export interface CatalogSyncResult {
  state: "ok" | "empty";
  rows: number;
  message: string;
}
export interface CalendarSyncResult {
  state: "ok";
  rows: number;
  message: string;
}
export interface InstrumentSearchRequest {
  query: string;
  offset: number;
}
export interface InstrumentPage {
  items: Array<Instrument>;
  total: number;
  offset: number;
}
export interface CalendarStatusRequest {
  date: string;
  exchange: Exchange;
}
export interface CalendarStatus {
  date: string;
  exchange: Exchange;
  sourceExchange: "SSE" | "SZSE";
  known: boolean;
  isOpen: boolean | null;
  previousTradeDate: string | null;
}
export interface BackupResult {
  path: string;
  files: number;
  bytes: number;
  sha256: string;
  createdAt: string;
}
export interface RestoreRequest {
  archive: string;
}
export interface RestoreResult {
  directory: string;
  overview: Overview;
  originalPreserved: true;
}
export interface ProfileValidation {
  valid: true;
  referencedFiles: number;
  overview: Overview;
}
export interface CompactionResult {
  converted: number;
  bundles: number;
  alreadyBundled: number;
  retainedOriginals: true;
}
export interface BarSyncRequest {
  token: string;
  instrumentId: string;
  start: string;
  end: string;
}
export interface FinancialSyncRequest {
  token: string;
  instrumentId: string;
  start: string;
  end: string;
  endpoint: FinancialEndpoint;
}
export interface BarSyncResult {
  snapshotId: string;
  rows: number;
  asOf: string;
  reused: boolean;
  repaired?: boolean;
}
export interface FinancialSyncResult {
  snapshotId: string;
  rows: number;
  asOf: string;
  repaired: boolean;
}
export type ProviderEndpoint = "stock_basic" | "trade_cal" | "daily" | "adj_factor" | "income" | "balancesheet" | "cashflow" | "daily_basic" | "index_daily" | "daily_info" | "sz_daily_info" | "anns_d" | "stk_limit" | "index_classify" | "index_member_all" | "sw_daily" | "stock_company" | "namechange" | "stk_managers" | "stk_rewards" | "stk_premarket" | "stock_st" | "st" | "stock_hsgt" | "bse_mapping" | "new_share" | "bak_basic" | "forecast" | "express" | "fina_indicator" | "fina_mainbz";
export interface DiagnosticRequest {
  token: string;
  endpoint: ProviderEndpoint;
}
export interface Diagnostic {
  endpoint: ProviderEndpoint;
  checkedAt: string;
  state: string;
  rows: number;
  message: string;
}
export interface SectorMember {
  instrumentId: string;
  name: string;
}
export interface SectorRow {
  id: string;
  name: string;
  close: number | null;
  pct: number | null;
  amount: number | null;
  members: Array<SectorMember>;
}
export interface SectorSnapshot {
  snapshotId: string;
  asOf: string;
  collectedAt: string;
  items: Array<SectorRow>;
}
export type SectorReadResult = SectorSnapshot | null;
export interface SectorHistory {
  snapshotId: string;
  sectorId: string;
  asOf: string;
  collectedAt: string;
  start: string;
  end: string;
  items: Array<IndexRow>;
}
export type SectorHistoryResult = SectorHistory | null;
export interface SectorRequest {
  sectorId: string;
}
export interface SectorHistoryParams {
  sectorId: string;
  start: string;
  end: string;
}
export interface SectorHistoryEnsure {
  sectorId: string;
  force: boolean;
  token: string;
}
export interface SectorSyncJobRequest {
  kind: "sectors.sync";
  params: BreadthSyncJobParams;
  token: string;
}
export interface SectorHistoryJobRequest {
  kind: "sector.history.sync";
  params: SectorHistoryParams;
  token: string;
}
export type JobResult = null | CatalogSyncResult | CalendarSyncResult | BarSyncResult | FinancialSyncResult | IndexSnapshot | MarketSnapshot | BreadthSnapshot | SectorSnapshot | SectorHistory | AnnouncementSyncResult | ReferenceSyncResult;
export interface Job {
  id: string;
  kind: string;
  state: string;
  createdAt: string;
  error: string | null;
  result: JobResult;
  retryId: string | null;
  profileId: string | null;
  idempotencyKey: string | null;
  startedAt: string | null;
  finishedAt: string | null;
  retryAt: string | null;
  inputSnapshot: string | null;
  attempt: number;
  generation: number;
  artifactIds: Array<string>;
}
export type JobList = Array<Job>;
export interface JobKey {
  id: string;
}
export interface JobRetryRequest {
  id: string;
  token: string;
}
export interface CancelAllResult {
  cancelled: number;
}
export interface CatalogSyncJobParams {
  exchange: Exchange;
  status: "L" | "D" | "P";
}
export interface CatalogSyncJobRequest {
  kind: "catalog.sync";
  token: string;
  params: CatalogSyncJobParams;
}
export interface CalendarSyncJobParams {
  exchange: "SSE" | "SZSE";
  year: number;
}
export interface CalendarSyncJobRequest {
  kind: "calendar.sync";
  token: string;
  params: CalendarSyncJobParams;
}
export interface BarSyncJobParams {
  instrumentId: string;
  start: string;
  end: string;
}
export interface BarSyncJobRequest {
  kind: "bars.sync";
  token: string;
  params: BarSyncJobParams;
}
export interface FinancialSyncJobParams {
  instrumentId: string;
  start: string;
  end: string;
  endpoint: FinancialEndpoint;
}
export interface FinancialSyncJobRequest {
  kind: "financials.sync";
  token: string;
  params: FinancialSyncJobParams;
}
export type JobEnqueueRequest = CatalogSyncJobRequest | CalendarSyncJobRequest | BarSyncJobRequest | FinancialSyncJobRequest | IndexSyncJobRequest | MarketSyncJobRequest | BreadthSyncJobRequest | SectorSyncJobRequest | SectorHistoryJobRequest | AnnouncementJobRequest | ReferenceJobRequest;
export interface EnabledPolicy {
  enabled: boolean;
}
export interface TokenRequest {
  token: string;
}
export interface AutoCalendarRequest {
  kind: "calendar.sync";
  params: CalendarSyncJobParams;
}
export interface AutoBarsRequest {
  kind: "bars.sync";
  params: BarSyncJobParams;
}
export interface AutoDormantPlan {
  state: "disabled" | "waiting";
  message: string;
  requests: Array<null>;
}
export interface AutoDormantDispatch {
  state: "disabled" | "waiting";
  message: string;
  submitted: Array<string>;
  remaining: number;
}
export interface AutoCalendarPlan {
  state: "calendar";
  message: string;
  requests: Array<AutoCalendarRequest>;
}
export interface AutoCalendarDispatch {
  state: "calendar";
  message: string;
  submitted: Array<string>;
  remaining: number;
}
export interface AutoReadyPlan {
  state: "ready";
  target: string;
  start: string;
  covered: number;
  attempted: number;
  total: number;
  message: string;
  requests: Array<AutoBarsRequest>;
}
export interface AutoReadyDispatch {
  state: "ready";
  target: string;
  start: string;
  covered: number;
  attempted: number;
  total: number;
  message: string;
  submitted: Array<string>;
  remaining: number;
}
export type AutoSyncPlan = AutoDormantPlan | AutoCalendarPlan | AutoReadyPlan;
export type AutoSyncDispatch = AutoDormantDispatch | AutoCalendarDispatch | AutoReadyDispatch;
export interface StockExample {
  id: string;
  name: string;
}
export type PoolScope = "all" | "watchlist";
export type PoolLookback = 1 | 20 | 60;
export interface AllPoolRequest {
  scope: "all";
  listId: null;
  date: string;
  lookback: PoolLookback;
}
export interface WatchlistPoolRequest {
  scope: "watchlist";
  listId: string;
  date: string;
  lookback: PoolLookback;
}
export type PoolPrepareRequest = AllPoolRequest | WatchlistPoolRequest;
export interface ScreenPoolPlan {
  planId: string;
  date: string;
  start: string;
  scope: PoolScope;
  lookback: PoolLookback;
  stocks: number;
  tasks: number;
  maxProviderRequests: number;
  examples: Array<StockExample>;
  bseCalendarProxy: boolean;
}
export interface ScreenBatch {
  planId: string;
  state: "running" | "paused" | "completed";
  completedTasks: number;
  totalTasks: number;
  stocks: number;
  date: string;
  start: string;
  currentJobId: string | null;
  error: string | null;
}
export type OptionalScreenBatch = ScreenBatch | null;
export interface BatchStartRequest {
  planId: string;
  token: string;
}
export interface RecapMissing {
  id: string;
  reason: string;
}
export interface RecapItem {
  id: string;
  name: string;
  date: string;
  close: number;
  amount: number;
  changePercent: number | null;
  previousDate: string | null;
  snapshotId: string;
  changeBasis: "复权收盘价相对上一交易日";
  calendarSource: "SSE" | "SZSE" | "SSE proxy";
}
export interface RecapReport {
  date: string;
  createdAt: string;
  kind: "deterministic";
  modelUsed: false;
  total: number;
  covered: number;
  up: number;
  down: number;
  unknownChange: number;
  missing: Array<RecapMissing>;
  items: Array<RecapItem>;
}
export type LatestRecap = RecapReport | null;
export interface ReadyRecap {
  state: "ready";
  reused: boolean;
  report: RecapReport;
}
export interface WaitingRecap {
  state: "waiting";
  message: string;
  report?: RecapReport;
}
export interface UnavailableRecap {
  state: "closed" | "empty";
  message: string;
}
export type RecapResult = ReadyRecap | WaitingRecap | UnavailableRecap;
export interface ModelRecapPolicy {
  enabled: boolean;
  dailyRequests: number;
  dailyMicroUsd: number;
}
export interface ModelRecapUsage {
  date: string;
  requests: number;
  chargedMicroUsd: number;
  unsettled: number;
}
export interface ModelReservation {
  date: string;
  requestKey: string;
  contextId: string | null;
  reservedMicroUsd: number;
  actualMicroUsd: number | null;
  state: "reserved" | "succeeded" | "failed" | "cancelled";
}
export type ModelRecapAttempt = ModelReservation | null;
export interface ModelReserveRequest {
  contextId: string;
  requestKey: string;
  reservedMicroUsd: number;
}
export interface ModelReserveResult {
  reservation: ModelReservation;
  dispatchAllowed: boolean;
}
export interface ModelSettleRequest {
  date: string;
  requestKey: string;
  actualMicroUsd: number | null;
  outcome: "succeeded" | "failed" | "cancelled";
}
export interface ModelContextRequest {
  contextId: string;
}
export interface ModelStockFact {
  id: string;
  instrumentId: string;
  field: "close" | "amount" | "changePercent";
  value: number;
  unit: "CNY" | "percent (adjusted close)";
  date: string;
  snapshotId: string;
}
export interface ModelAggregateFact {
  id: string;
  field: "total" | "covered" | "up" | "down" | "unknownChange";
  value: number;
  unit: "stocks";
  date: string;
}
export type ModelRecapFact = ModelStockFact | ModelAggregateFact;
export interface ModelRecapInput {
  date: string;
  facts: Array<ModelRecapFact>;
  source: RecapReport;
  limitations: Array<string>;
}
export interface ModelRecapContext {
  contextId: string;
  requestKey: string;
  input: ModelRecapInput;
}
export interface ModelRecapObservation {
  text: string;
  factIds: Array<string>;
}
export interface ModelRecapContent {
  summary: string;
  observations: Array<ModelRecapObservation>;
  limitations: Array<string>;
}
export interface ModelPublishRequest {
  contextId: string;
  model: "gpt-4.1-mini-2025-04-14";
  report: ModelRecapContent;
}
export interface ModelPublishedRecap {
  contextId: string;
  model: "gpt-4.1-mini-2025-04-14";
  report: ModelRecapContent;
  date: string;
  requestKey: string;
  estimatedMicroUsd: number | null;
  reservedMicroUsd: number;
}
export type LatestModelRecap = ModelPublishedRecap | null;
export interface ResearchRunRequest {
  runId: string;
}
export interface ResearchPrepareRequest {
  instrumentIds: Array<string>;
  question: string;
  requestKey?: string;
}
export interface ResearchFact {
  id: string;
  instrumentId: string;
  field: string;
  value: number | null;
  unit: string;
  date: string;
  snapshotId: string;
  annDate?: string | null;
  ambiguousRevision?: boolean;
}
export interface ResearchIncome {
  manifest: IncomeManifest;
  items: Array<IncomeRow>;
}
export interface ResearchBalance {
  manifest: BalanceManifest;
  items: Array<BalanceRow>;
}
export interface ResearchCashflow {
  manifest: CashflowManifest;
  items: Array<CashflowRow>;
}
export interface ResearchValuation {
  manifest: ValuationManifest;
  items: Array<ValuationRow>;
}
export interface ResearchFinancials {
  income?: ResearchIncome;
  balancesheet?: ResearchBalance;
  cashflow?: ResearchCashflow;
  daily_basic?: ResearchValuation;
}
export interface ResearchInstrument {
  id: string;
  name: string;
  exchange: "SSE" | "SZSE" | "BSE";
  barSnapshotId: string | null;
  financials: ResearchFinancials;
  barAsOf?: string;
  forwardAnchor?: string | null;
}
export interface ResearchMissing {
  instrumentId: string;
  dataset: "daily" | "income" | "balancesheet" | "cashflow" | "daily_basic";
  reason: string;
}
export interface ResearchContext {
  runId: string;
  question: string;
  createdAt: string;
  instruments: Array<ResearchInstrument>;
  facts: Array<ResearchFact>;
  missing: Array<ResearchMissing>;
  strictPointInTime: false;
}
export type ResearchState = "prepared" | "running" | "succeeded" | "cancelled" | "failed" | "interrupted";
export interface ResearchStart {
  runId: string;
  state: ResearchState;
  started: boolean;
}
export interface ResearchStop {
  runId: string;
  state: "cancelled" | "failed";
}
export interface ResearchEventRequest {
  runId: string;
  stage: "starting" | "analyzing" | "saving" | "cancelling";
}
export interface ResearchRecorded {
  recorded: true;
}
export interface ResearchEventsRequest {
  runId: string;
  after: number;
}
export interface ResearchEvent {
  sequence: number;
  stage: "prepared" | "running" | "starting" | "analyzing" | "saving" | "cancelling" | "draft_saved" | "succeeded" | "failed" | "cancelled" | "interrupted";
  createdAt: string;
}
export interface ResearchEvents {
  items: Array<ResearchEvent>;
  nextCursor: number;
  state: ResearchState;
}
export interface ResearchValue {
  factId: string;
  value: number;
  unit: string;
  date: string;
}
export interface ResearchClaim {
  text: string;
  factIds: Array<string>;
  values?: Array<ResearchValue>;
}
export interface ResearchNewClaim {
  text: string;
  factIds: Array<string>;
  values: Array<ResearchValue>;
}
export interface ResearchContent {
  summary: string;
  claims: Array<ResearchClaim>;
  limitations: Array<string>;
}
export interface ResearchNewContent {
  summary: string;
  claims: Array<ResearchNewClaim>;
  limitations: Array<string>;
}
export interface ResearchDraftRequest {
  runId: string;
  report: ResearchNewContent;
}
export interface ResearchDraftSaved {
  runId: string;
  draftId: string;
  state: "draft";
  published: false;
}
export interface ResearchDraftPayload {
  runId: string;
  report: ResearchNewContent;
  contextSha256: string;
}
export interface ResearchDraft {
  draftId: string;
  payload: ResearchDraftPayload;
}
export interface ResearchUsage {
  input_tokens: number;
  output_tokens: number;
  cached_input_tokens: number;
}
export interface ResearchSaveRequest {
  runId: string;
  report: ResearchNewContent;
  model: string;
  threadId: string;
  usage: ResearchUsage;
}
export interface ResearchPayload {
  runId: string;
  report: ResearchContent;
  model: string;
  threadId: string;
  usage: ResearchUsage;
  createdAt: string;
  contextSha256: string;
  draftId?: string;
}
export interface ResearchReport {
  payload: ResearchPayload;
  context: ResearchContext;
}
export interface ResearchListRequest {
  offset: number;
}
export interface ResearchEntry {
  runId: string;
  state: ResearchState;
  createdAt: string;
}
export interface ResearchList {
  items: Array<ResearchEntry>;
  total: number;
}
export interface ResearchExport {
  filename: string;
  mimeType: "text/markdown;charset=utf-8";
  content: string;
}
export interface ResearchChartRequest {
  runId: string;
  instrumentId: string;
}
export interface ResearchChart {
  artifactId: string;
  runId: string;
  instrumentId: string;
  snapshotId: string;
  asOf: string;
  adjustment: "forward";
  anchor: string | null;
  rows: number;
  mimeType: "image/svg+xml";
  svg: string;
}
export interface ServiceHealth {
  protocolVersion: 2;
  schemaVersion: number;
  instruments: number;
  watchlists: number;
  jobs: number;
  reports: number;
  settings: Settings;
  dataAsOf: string | null;
  contractFingerprint: string;
}
export interface RpcMetadata {
  dataAsOf: string | null;
  sourceVersion: string | null;
}
export interface WatchlistRenameRequest {
  listId: string;
  name: string;
}
export interface HoldingSaveRequest {
  instrumentId: string;
  quantity: number;
  costPrice: string | null;
  asOf: string;
  revision: number;
}
export interface Holding {
  instrumentId: string;
  quantity: number;
  costPrice: string | null;
  asOf: string;
  revision: number;
  name: string;
  updatedAt: string;
}
export type HoldingList = Array<Holding>;
export interface HoldingValuation {
  holding: Holding;
  price: string | null;
  priceDate: string | null;
  snapshotId: string | null;
  provider: "tushare" | null;
  marketValue: string | null;
  floatingProfit: string | null;
  profitPercent: string | null;
  pricedHoldingsPercent: string | null;
  status: "closed" | "missingPrice" | "priceBeforeHolding" | "valued" | "dataError";
  costBasis: string | null;
  realizedProfit: string | null;
}
export interface HoldingsSummary {
  account: HoldingAccount;
  items: Array<HoldingValuation>;
  pricedMarketValue: string;
  marketValue: string | null;
  floatingProfit: string | null;
  missingPriceCount: number;
  missingCostCount: number;
  valuationBasis: "latest-unadjusted-close";
  weightBasis: "priced-open-holdings-excluding-cash";
  costBasis: string | null;
  knownCostBasis: string;
  unknownCostCount: number;
  realizedProfit: string | null;
  knownRealizedProfit: string;
  unknownRealizedCount: number;
  priceDates: Array<string>;
  industries: Array<PortfolioIndustry>;
  industryStatus: "ready" | "missing" | "error";
  industryCollectedAt: string | null;
}
export interface HoldingAccount {
  id: "manual";
  name: "项目手动持仓";
  currency: "CNY";
  cash: null;
}
export interface LatestQuote {
  instrumentId: string;
  close: number | null;
  date: string | null;
  collectedAt: string | null;
  snapshotId: string | null;
  status: "available" | "missing" | "dataError";
}
export type LatestQuoteList = Array<LatestQuote>;
export interface LatestQuoteRequest {
  instrumentIds: Array<string>;
}
export interface DemandPolicy {
  enabled: boolean;
  intervalMinutes: 15 | 60 | 240;
}
export interface DemandEnsureRequest {
  instrumentId: string;
  endpoint: "bars" | "daily_basic" | "income" | "balancesheet" | "cashflow";
  years: 1 | 3 | 4;
  force: boolean;
  token: string;
}
export interface DemandState {
  state: "ready" | "updating" | "failed" | "disabled";
  message: string;
  jobIds: Array<string>;
}
export interface SectorSummaryRow {
  id: string;
  name: string;
  close: number | null;
  pct: number | null;
  amount: number | null;
  memberCount: number;
}
export interface SectorSummary {
  snapshotId: string;
  asOf: string;
  collectedAt: string;
  items: Array<SectorSummaryRow>;
}
export type SectorSummaryResult = SectorSummary | null;
export interface SectorMembersRequest {
  sectorId: string;
  offset: number;
}
export interface SectorMembers {
  sectorId: string;
  collectedAt: string;
  total: number;
  offset: number;
  items: Array<SectorMember>;
}
export interface PortfolioIndustry {
  id: string | null;
  name: string;
  marketValue: string;
  holdingCount: number;
  missingPriceCount: number;
  pricedHoldingsPercent: string | null;
}
export const PROVIDER_ENDPOINTS = ["stock_basic","trade_cal","daily","adj_factor","income","balancesheet","cashflow","daily_basic","index_daily","daily_info","sz_daily_info","anns_d","stk_limit","index_classify","index_member_all","sw_daily","stock_company","namechange","stk_managers","stk_rewards","stk_premarket","stock_st","st","stock_hsgt","bse_mapping","new_share","bak_basic","forecast","express","fina_indicator","fina_mainbz"] as const;
