import {spawnSync} from 'node:child_process';
import path from 'node:path';
import fs from 'node:fs';
import {randomUUID,createHash} from 'node:crypto';
const contracts=spawnSync(process.execPath,['scripts/generate-contracts.mjs','--check'],{stdio:'inherit',windowsHide:true});
if(contracts.status!==0)throw Error('Contract generation check failed');
const python=path.resolve(process.platform==='win32'?'.venv312/Scripts/python.exe':'.venv312/bin/python');
if(!fs.existsSync(python))throw Error('Create .venv312 and install requirements-build.txt first.');
const inspect=spawnSync(python,['-c',"import platform,ssl,sqlite3,json,duckdb,PyInstaller,sys; print(json.dumps({'python':platform.python_version(),'architecture':platform.machine(),'openssl':ssl.OPENSSL_VERSION,'sqlite':sqlite3.sqlite_version,'duckdb':duckdb.__version__,'pyinstaller':PyInstaller.__version__,'basePrefix':sys.base_prefix}))"],{encoding:'utf8',windowsHide:true});
if(inspect.status!==0)throw Error('Build runtime inspection failed.');
const {basePrefix,...runtime}=JSON.parse(inspect.stdout);
if(runtime.python!=='3.12.14'||runtime.architecture!=='AMD64')throw Error('Expected pinned Python 3.12.14 Windows x64 environment.');
const directory=path.resolve('build/service-builds',randomUUID());fs.mkdirSync(directory,{recursive:true});
const systemRoot=process.env.SystemRoot??process.env.SYSTEMROOT;
if(!systemRoot||!path.isAbsolute(systemRoot)||!path.isAbsolute(basePrefix))throw Error('Missing explicit runtime/system directories');
const buildEnv={...process.env};
for(const key of Object.keys(buildEnv))if(['PATH','PYTHONPATH','PYTHONHOME'].includes(key.toUpperCase()))delete buildEnv[key];
buildEnv.PATH=[path.dirname(python),basePrefix,path.join(basePrefix,'DLLs'),path.join(systemRoot,'System32'),systemRoot].join(path.delimiter);
buildEnv.STOCK_SERVICE_ENTRY=path.resolve('apps/data-service/main.py');
const spec=path.join(directory,'stock-data.spec');fs.copyFileSync(path.resolve('scripts/data-service.spec'),spec);
const result=spawnSync(python,['-m','PyInstaller','--distpath',path.join(directory,'dist'),'--workpath',path.join(directory,'work'),spec],{stdio:'inherit',windowsHide:true,env:buildEnv});
if(result.status!==0)process.exit(result.status??1);
const service=path.join(directory,'dist/stock-data'),binary=path.join(service,'stock-data.exe');
const schemaVersion=Number(fs.readFileSync('apps/data-service/schema.py','utf8').match(/^SCHEMA_VERSION = (\d+)$/m)?.[1]);
if(!Number.isSafeInteger(schemaVersion)||schemaVersion<5)throw Error('Invalid schema version');
const record={createdAt:new Date().toISOString(),directory:service,runtime,schemaVersion,binarySha256:createHash('sha256').update(fs.readFileSync(binary)).digest('hex')};
fs.writeFileSync(path.join(service,'runtime.json'),JSON.stringify({runtime,binarySha256:record.binarySha256},null,2));
fs.writeFileSync('build/service-current.json',JSON.stringify(record,null,2));
console.log('Service built in isolated directory:',service);

